#!/usr/bin/env python3
"""Add curated meals to fill cuisine gaps in src/data/meals.json.

Targets cuisines with 1-3 meals; bumps the most underrepresented ones to
4-6 so the diet+cuisine filter feels usable across the long tail. Each
meal carries realistic ingredient_categories, tags, serving_grams, and
contains markers for pork / alcohol where applicable.

After this runs, scripts/rederive_diet_compatibility.py should be
re-run to populate diet_compatibility on the new meals.

Run from project root:
    python scripts/add_curated_meals_cuisine_gaps.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PATH = ROOT / 'src' / 'data' / 'meals.json'


def meal(id, name, cuisine, cats, notes, serving_grams, tags=('dinner', 'lunch'),
         contains=None, source='curated'):
    rec = {
        'id': id,
        'name': name,
        'ingredient_categories': list(cats),
        'notes': notes,
        'cuisine': cuisine,
        'frequency': 1,
        'source': source,
        'tags': list(tags),
        'serving_grams': serving_grams,
    }
    if contains:
        rec['contains'] = sorted(set(contains))
    # diet_compatibility deliberately omitted — re-derived later.
    return rec


# Helpers for tag tuples
DL = ('dinner', 'lunch')
DESS = ('dessert',)
BRK = ('breakfast',)
SNK = ('snack',)
LSN = ('lunch', 'snack')


NEW_MEALS = [
    # ────────────────────────── Bangladeshi ──────────────────────────
    meal('bengali-hilsa-curry', 'Hilsa curry (shorshe ilish)', 'Bangladeshi',
         ['Freshwater fish', 'Pastes & ferments', 'Peppers & nightshades', 'Oils',
          'Ground spices', 'Salt & seasonings'],
         "Hilsa fish poached in a mustard-paste curry — the national fish of Bangladesh, fragrant with green chilies and pungent mustard oil.",
         320, DL),
    meal('bengali-cholar-dal', 'Cholar dal (Bengali chana dal)', 'Bangladeshi',
         ['Legumes', 'Cream & butter', 'Whole spices', 'Ground spices', 'Dried fruits',
          'Citrus'],
         "Bengal-style split chickpea lentils tempered with bay leaf, cumin, and ghee, garnished with raisins and coconut.",
         300, DL),
    meal('bengali-mishti-doi', 'Mishti doi', 'Bangladeshi',
         ['Yogurt', 'Milk', 'Sugar & sweeteners'],
         "Caramelized sweet yogurt set in clay pots — Bengal's signature dessert.",
         140, DESS),
    meal('bengali-roshogolla', 'Roshogolla', 'Bangladeshi',
         ['Fresh cheese', 'Sugar & sweeteners', 'Extracts & essences'],
         "Spongy chhana cheese balls simmered in light sugar syrup, fragrant with cardamom.",
         120, DESS),
    meal('bengali-bhuna-khichuri', 'Bhuna khichuri', 'Bangladeshi',
         ['Refined grains', 'Legumes', 'Oils', 'Ground spices', 'Whole spices',
          'Other vegetables'],
         "Rice and lentils browned together with whole spices — Bengal's monsoon comfort dish.",
         400, DL),

    # ────────────────────────── Pakistani / Pashtun ──────────────────────
    meal('chicken-karahi', 'Chicken karahi', 'Pakistani',
         ['Poultry', 'Peppers & nightshades', 'Ground spices', 'Fresh herbs',
          'Salt & seasonings', 'Oils'],
         "Chicken seared and simmered in a wok-style karahi with tomatoes, ginger, green chilies, and a finishing splash of cream.",
         380, DL),
    meal('beef-nihari-pakistani', 'Beef nihari (Pakistani)', 'Pakistani',
         ['Red meat', 'Ground spices', 'Spice blends', 'Bread & rolls',
          'Oils', 'Citrus'],
         "Overnight-slow-cooked beef shank in a thick spiced gravy, traditionally served at breakfast with naan.",
         400, DL),
    meal('seekh-kebab-pakistani', 'Seekh kebab', 'Pakistani',
         ['Red meat', 'Fresh herbs', 'Ground spices', 'Peppers & nightshades',
          'Bread & rolls', 'Other vegetables'],
         "Spiced minced lamb skewers grilled over coals, served with mint chutney and warm flatbread.",
         300, DL),
    meal('kabuli-pulao', 'Kabuli pulao', 'Pakistani-Pashtun',
         ['Refined grains', 'Red meat', 'Dried fruits', 'Nuts',
          'Whole spices', 'Oils', 'Other vegetables'],
         "Afghan-Pashtun pulao with lamb, caramelized carrots, raisins, and almonds layered over fluffy basmati.",
         420, DL),
    meal('mantu-dumplings', 'Mantu', 'Pakistani-Pashtun',
         ['Bread & rolls', 'Red meat', 'Yogurt', 'Other vegetables',
          'Ground spices', 'Salt & seasonings'],
         "Steamed lamb dumplings topped with garlic yogurt and a lentil-tomato sauce — Pashtun comfort food.",
         320, DL),

    # ────────────────────────── Tunisian / North African ─────────────────
    meal('tunisian-couscous', 'Tunisian couscous', 'Tunisian',
         ['Refined grains', 'Red meat', 'Other vegetables', 'Legumes',
          'Peppers & nightshades', 'Ground spices', 'Oils'],
         "Tunisian-style couscous with lamb, chickpeas, harissa-spiced broth, and stewed vegetables.",
         400, DL),
    meal('lablabi-tunisian', 'Lablabi', 'Tunisian',
         ['Legumes', 'Bread & rolls', 'Oils', 'Eggs',
          'Ground spices', 'Citrus', 'Peppers & nightshades'],
         "Tunisian chickpea soup served over torn bread, topped with cumin, harissa, olive oil, and a poached egg.",
         350, DL),
    meal('pastilla-moroccan', 'Pastilla (b\'stilla)', 'North African',
         ['Poultry', 'Baked snacks & pastries', 'Nuts', 'Eggs',
          'Ground spices', 'Sugar & sweeteners', 'Whole spices'],
         "Phyllo pie of spiced shredded pigeon (or chicken), almonds, and saffron eggs, dusted with cinnamon sugar.",
         280, DL),
    meal('couscous-royale-north-african', 'Couscous royale', 'North African',
         ['Refined grains', 'Red meat', 'Poultry', 'Processed meat',
          'Other vegetables', 'Legumes', 'Peppers & nightshades', 'Ground spices'],
         "Heaped Maghreb-style couscous platter with lamb, chicken, merguez sausage, and seven vegetables in saffron broth.",
         450, DL),

    # ────────────────────────── West Africa ──────────────────────────────
    meal('jollof-rice-ghanaian', 'Ghanaian jollof rice', 'Ghanaian',
         ['Refined grains', 'Peppers & nightshades', 'Other vegetables',
          'Poultry', 'Oils', 'Ground spices', 'Salt & seasonings'],
         "Ghana's smoky one-pot jollof — long-grain rice cooked down in a tomato-pepper-onion base, served with grilled chicken.",
         400, DL),
    meal('kelewele-ghanaian', 'Kelewele', 'Ghanaian',
         ['Tropical fruits', 'Ground spices', 'Oils', 'Peppers & nightshades',
          'Salt & seasonings'],
         "Cubed ripe plantains tossed in ginger, chili, and warm spices, then deep-fried — a West African street snack.",
         180, SNK),
    meal('red-red-ghanaian', 'Red red (bean stew)', 'Ghanaian',
         ['Legumes', 'Peppers & nightshades', 'Other vegetables', 'Oils',
          'Ground spices'],
         "Cowpea stew in a vivid palm-oil and tomato sauce, served with fried plantains.",
         350, DL),
    meal('yassa-poulet', 'Yassa poulet', 'Senegalese',
         ['Poultry', 'Citrus', 'Other vegetables', 'Pickled vegetables',
          'Oils', 'Refined grains'],
         "Marinated chicken braised with caramelized onions and lemon mustard sauce, served over rice.",
         400, DL),
    meal('mafe-senegalese', 'Mafé', 'Senegalese',
         ['Red meat', 'Nut butters', 'Other vegetables', 'Starchy vegetables',
          'Peppers & nightshades', 'Refined grains'],
         "Senegalese peanut-butter stew with lamb, root vegetables, and tomatoes, served over rice.",
         400, DL),
    meal('pepper-soup-nigerian', 'Nigerian pepper soup', 'West African-Nigerian',
         ['Red meat', 'Peppers & nightshades', 'Fresh herbs', 'Ground spices',
          'Prepared soups & broths'],
         "Aromatic clear broth with goat meat, scotch bonnets, calabash nutmeg, and uziza leaves.",
         350, DL),
    meal('suya-skewers-nigerian', 'Suya (yaji-rubbed beef)', 'West African-Nigerian',
         ['Red meat', 'Nuts', 'Ground spices', 'Spice blends',
          'Peppers & nightshades', 'Oils'],
         "Thinly-sliced beef coated in peanut-pepper yaji rub and grilled over coals — Nigeria's street kebab.",
         280, DL),

    # ────────────────────────── East Africa ──────────────────────────────
    meal('nyama-choma', 'Nyama choma', 'Kenyan',
         ['Red meat', 'Salt & seasonings', 'Other vegetables', 'Peppers & nightshades'],
         "Charcoal-roasted goat served with kachumbari (tomato-onion-cilantro relish) — Kenya's grill-out staple.",
         350, DL),
    meal('kenyan-pilau', 'Kenyan pilau', 'Kenyan',
         ['Refined grains', 'Red meat', 'Other vegetables', 'Whole spices',
          'Ground spices', 'Oils'],
         "Rice spiced with cumin, cinnamon, cardamom, and cloves, slow-cooked with beef stock and chunks of meat.",
         400, DL),
    meal('chapati-kenyan', 'Kenyan chapati', 'Kenyan',
         ['Flours', 'Oils', 'Salt & seasonings'],
         "Layered, flaky chapati fried on a hot griddle — eaten with stews across East Africa.",
         100, DL),

    # ────────────────────────── Caribbean / Latin ────────────────────────
    meal('pelau-trinidadian', 'Pelau', 'Trinidadian',
         ['Refined grains', 'Poultry', 'Legumes', 'Other vegetables',
          'Peppers & nightshades', 'Sugar & sweeteners', 'Oils'],
         "Caramel-browned chicken, pigeon peas, and rice braised together with thyme and Scotch bonnet.",
         420, DL),
    meal('doubles-trinidadian', 'Doubles', 'Trinidadian',
         ['Legumes', 'Bread & rolls', 'Ground spices', 'Sauces',
          'Peppers & nightshades'],
         "Two soft bara flatbreads holding curried chickpeas, tamarind, and pepper sauce — Trinidad's iconic breakfast street food.",
         200, BRK),
    meal('pernil-puerto-rican', 'Pernil', 'Puerto Rican',
         ['Red meat', 'Citrus', 'Fresh herbs', 'Ground spices', 'Salt & seasonings',
          'Other vegetables'],
         "Slow-roasted pork shoulder marinated in adobo and sour-orange mojo, with crackling skin.",
         380, DL, contains=['pork']),
    meal('arroz-con-gandules', 'Arroz con gandules', 'Puerto Rican',
         ['Refined grains', 'Legumes', 'Processed meat', 'Other vegetables',
          'Peppers & nightshades', 'Oils', 'Fresh herbs'],
         "Puerto Rico's national rice — pigeon peas, sofrito, and pork-based seasoning blend.",
         380, DL, contains=['pork']),
    meal('casado-costa-rican', 'Casado', 'Costa Rican',
         ['Refined grains', 'Legumes', 'Eggs', 'Other vegetables',
          'Starchy vegetables', 'Tropical fruits', 'Red meat'],
         "Plate lunch with rice, black beans, fried plantain, salad, and a protein — beef, chicken, or fish.",
         450, DL),
    meal('soup-joumou-haitian', 'Soup joumou', 'Haitian',
         ['Starchy vegetables', 'Red meat', 'Other vegetables', 'Prepared soups & broths',
          'Refined grains', 'Citrus', 'Fresh herbs'],
         "Haiti's Independence Day soup — pureed squash, beef, pasta, and vegetables.",
         400, DL),
    meal('moros-y-cristianos', 'Moros y cristianos', 'Cuban',
         ['Refined grains', 'Legumes', 'Processed meat', 'Peppers & nightshades',
          'Other vegetables', 'Oils', 'Fresh herbs'],
         "Cuban black beans and rice cooked together with sofrito and a touch of bacon.",
         380, DL, contains=['pork']),
    meal('yuca-con-mojo', 'Yuca con mojo', 'Cuban',
         ['Starchy vegetables', 'Oils', 'Citrus', 'Other vegetables',
          'Fresh herbs', 'Salt & seasonings'],
         "Boiled cassava bathed in a garlicky sour-orange and olive-oil sauce.",
         250, DL),

    # ────────────────────────── Eastern Europe ────────────────────────────
    meal('bigos-polish', 'Bigos (hunter\'s stew)', 'Polish',
         ['Pickled vegetables', 'Processed meat', 'Red meat', 'Other vegetables',
          'Mushrooms', 'Whole spices', 'Salt & seasonings'],
         "Long-simmered Polish stew of sauerkraut, pork, sausage, and beef — even better the next day.",
         400, DL, contains=['pork']),
    meal('kotlet-schabowy', 'Kotlet schabowy', 'Polish',
         ['Red meat', 'Eggs', 'Bread & rolls', 'Oils',
          'Starchy vegetables', 'Pickled vegetables'],
         "Breaded fried pork cutlet, served with mashed potatoes and cucumber-dill salad.",
         380, DL, contains=['pork']),
    meal('zurek-polish', 'Żurek', 'Polish',
         ['Prepared soups & broths', 'Processed meat', 'Eggs', 'Starchy vegetables',
          'Cream & butter', 'Salt & seasonings', 'Fresh herbs'],
         "Tangy fermented-rye sour soup with white sausage and hard-boiled egg.",
         350, DL, contains=['pork']),
    meal('chicken-paprikash', 'Chicken paprikash', 'Hungarian',
         ['Poultry', 'Ground spices', 'Cream & butter', 'Fermented dairy',
          'Refined grains', 'Peppers & nightshades', 'Other vegetables'],
         "Chicken simmered in a sweet-paprika and sour-cream sauce, served over egg noodles.",
         400, DL),
    meal('lecso-hungarian', 'Lecsó', 'Hungarian',
         ['Peppers & nightshades', 'Other vegetables', 'Ground spices', 'Oils',
          'Eggs', 'Processed meat'],
         "Pepper-and-tomato stew finished with a sausage and a soft-set egg.",
         300, DL),
    meal('beef-stroganoff-russian', 'Beef stroganoff', 'Russian',
         ['Red meat', 'Mushrooms', 'Fermented dairy', 'Refined grains',
          'Cream & butter', 'Other vegetables', 'Fresh herbs'],
         "Tender beef and mushrooms in a sour-cream sauce, served over egg noodles or rice.",
         400, DL),
    meal('pelmeni-russian', 'Pelmeni', 'Russian',
         ['Bread & rolls', 'Red meat', 'Fermented dairy', 'Cream & butter',
          'Fresh herbs', 'Salt & seasonings'],
         "Siberian boiled dumplings filled with seasoned ground meat, served with butter and sour cream.",
         320, DL),
    meal('olivier-salad-russian', 'Olivier salad', 'Russian',
         ['Other vegetables', 'Eggs', 'Poultry', 'Pickled vegetables',
          'Starchy vegetables', 'Dressings & dips', 'Salt & seasonings'],
         "Russian holiday potato salad with chicken, eggs, pickles, and peas in a mayo dressing.",
         250, DL),
    meal('borscht-ukrainian', 'Ukrainian borscht', 'Eastern European',
         ['Starchy vegetables', 'Other vegetables', 'Salt & seasonings',
          'Red meat', 'Fermented dairy', 'Fresh herbs', 'Citrus'],
         "Beet-forward sour soup with beef, cabbage, and a finishing dollop of smetana.",
         350, DL),
    meal('goulash-soup-hungarian', 'Hungarian gulyás', 'Hungarian',
         ['Red meat', 'Starchy vegetables', 'Peppers & nightshades',
          'Other vegetables', 'Ground spices', 'Oils', 'Prepared soups & broths'],
         "Sweet-paprika beef stew with potatoes and peppers, looser and brothier than the American casserole.",
         400, DL),

    # ────────────────────────── Scandinavia ──────────────────────────────
    meal('janssons-frestelse', 'Jansson\'s frestelse', 'Swedish',
         ['Starchy vegetables', 'Canned & cured fish', 'Cream & butter',
          'Milk', 'Other vegetables', 'Bread & rolls', 'Salt & seasonings'],
         "Swedish gratin of sliced potato, sprats, and onion baked in cream — classic Christmas table dish.",
         350, DL),
    meal('kottbullar-with-lingonberry', 'Köttbullar', 'Swedish',
         ['Red meat', 'Eggs', 'Bread & rolls', 'Milk',
          'Cream & butter', 'Berries', 'Sauces', 'Starchy vegetables'],
         "Swedish meatballs in a cream gravy with mashed potato and lingonberry jam.",
         380, DL),
    meal('smorrebrod-open-sandwich', 'Smørrebrød', 'Danish',
         ['Bread & rolls', 'Canned & cured fish', 'Eggs', 'Other vegetables',
          'Cream & butter', 'Pickled vegetables', 'Fresh herbs'],
         "Danish open-faced rye bread with herring, sliced egg, dill, and pickled onion.",
         200, DL),
    meal('frikadeller-danish', 'Frikadeller', 'Danish',
         ['Red meat', 'Eggs', 'Bread & rolls', 'Milk',
          'Cream & butter', 'Starchy vegetables', 'Other vegetables'],
         "Danish pan-fried pork-and-veal meatballs with red cabbage and boiled potatoes.",
         380, DL, contains=['pork']),
    meal('gravadlax-platter', 'Gravlax with dill mustard', 'Scandinavian',
         ['Canned & cured fish', 'Bread & rolls', 'Sauces', 'Fresh herbs',
          'Cream & butter', 'Citrus'],
         "Cured salmon with dill-mustard sauce, served on rye crisp.",
         220, DL),

    # ────────────────────────── German / Austrian ─────────────────────────
    meal('sauerkraut-and-wurst', 'Sauerkraut and bratwurst', 'German',
         ['Pickled vegetables', 'Processed meat', 'Starchy vegetables',
          'Sauces', 'Salt & seasonings', 'Whole spices'],
         "Slow-braised sauerkraut with bratwurst and seared potatoes.",
         400, DL, contains=['pork']),
    meal('konigsberger-klopse', 'Königsberger Klopse', 'German',
         ['Red meat', 'Eggs', 'Bread & rolls', 'Pickled vegetables',
          'Cream & butter', 'Fermented dairy', 'Starchy vegetables', 'Citrus'],
         "East-Prussian veal meatballs in a creamy caper-lemon sauce.",
         380, DL),
    meal('tafelspitz-austrian', 'Tafelspitz', 'Austrian',
         ['Red meat', 'Other vegetables', 'Starchy vegetables', 'Fresh herbs',
          'Sauces', 'Cream & butter', 'Salt & seasonings'],
         "Boiled beef rump simmered with root vegetables, served with apple-horseradish sauce and chive cream.",
         400, DL),

    # ────────────────────────── Iberian / Portuguese ──────────────────────
    meal('caldo-verde', 'Caldo verde', 'Portuguese',
         ['Leafy greens', 'Starchy vegetables', 'Processed meat', 'Oils',
          'Prepared soups & broths', 'Salt & seasonings'],
         "Galician-style potato-and-kale soup with sliced chouriço.",
         350, DL, contains=['pork']),
    meal('piri-piri-chicken', 'Piri-piri chicken', 'Portuguese',
         ['Poultry', 'Peppers & nightshades', 'Citrus', 'Oils',
          'Ground spices', 'Salt & seasonings'],
         "Butterflied chicken marinated in bird's-eye chili, lemon, and garlic, then flame-grilled.",
         380, DL),
    meal('gambas-al-ajillo', 'Gambas al ajillo', 'Spanish',
         ['Shellfish', 'Oils', 'Peppers & nightshades', 'Fresh herbs',
          'Bread & rolls', 'Citrus'],
         "Garlic shrimp sizzled in olive oil with dried chili, served with crusty bread.",
         220, DL),
    meal('pulpo-a-la-gallega', 'Pulpo a la gallega', 'Spanish',
         ['Shellfish', 'Starchy vegetables', 'Oils', 'Ground spices',
          'Salt & seasonings'],
         "Boiled octopus over sliced potatoes, dusted with smoked paprika and sea salt.",
         300, DL),
    meal('albondigas-spanish', 'Albóndigas', 'Spanish',
         ['Red meat', 'Bread & rolls', 'Eggs', 'Sauces',
          'Peppers & nightshades', 'Fresh herbs'],
         "Spanish meatballs simmered in a tomato-almond sauce.",
         300, DL),

    # ────────────────────────── Greek ──────────────────────────────────
    meal('gyros-plate', 'Gyros plate', 'Greek',
         ['Red meat', 'Bread & rolls', 'Other vegetables', 'Dressings & dips',
          'Pickled vegetables', 'Citrus', 'Salt & seasonings'],
         "Vertical-roasted pork or lamb shaved off the spit, served with pita, tzatziki, tomato, and red onion.",
         350, DL),
    meal('pastitsio-greek', 'Pastitsio', 'Greek',
         ['Refined grains', 'Red meat', 'Aged cheese', 'Cream & butter',
          'Milk', 'Eggs', 'Ground spices', 'Peppers & nightshades'],
         "Greek baked pasta — long ziti, spiced lamb ragù, and a thick béchamel top crust.",
         380, DL),
    meal('horiatiki-salad', 'Horiatiki (Greek village salad)', 'Greek',
         ['Other vegetables', 'Peppers & nightshades', 'Fresh cheese',
          'Pickled vegetables', 'Oils', 'Fresh herbs', 'Salt & seasonings'],
         "Tomato, cucumber, onion, green pepper, kalamata olives, and a slab of feta — no lettuce.",
         280, DL),

    # ────────────────────────── East Asia (rounding out subcategories) ────
    meal('beef-noodle-soup-taiwan', 'Taiwanese beef noodle soup', 'Taiwanese',
         ['Refined grains', 'Red meat', 'Prepared soups & broths', 'Pastes & ferments',
          'Other vegetables', 'Ground spices', 'Whole spices', 'Fresh herbs'],
         "Soy-braised beef shank and tendon over wheat noodles in a rich, mahogany-colored broth.",
         500, DL),
    meal('lu-rou-fan', 'Lu rou fan', 'Taiwanese',
         ['Refined grains', 'Red meat', 'Eggs', 'Sauces',
          'Pickled vegetables', 'Whole spices'],
         "Taiwanese braised pork belly minced over rice with a tea-egg and pickled greens.",
         350, DL, contains=['pork']),
    meal('gua-bao', 'Gua bao', 'Taiwanese',
         ['Bread & rolls', 'Red meat', 'Pickled vegetables', 'Nuts',
          'Sauces', 'Fresh herbs', 'Sugar & sweeteners'],
         "Steamed bun stuffed with braised pork belly, pickled mustard greens, peanut powder, and cilantro.",
         220, DL, contains=['pork']),
    meal('hot-and-sour-soup', 'Hot and sour soup', 'Chinese',
         ['Prepared soups & broths', 'Soy products', 'Mushrooms',
          'Eggs', 'Sauces', 'Other vegetables'],
         "Sichuan-style soup with tofu, wood-ear mushrooms, bamboo shoots, and a pepper-vinegar punch.",
         350, DL),
    meal('mongolian-beef-chinese', 'Mongolian beef', 'Chinese-American',
         ['Red meat', 'Other vegetables', 'Sauces', 'Refined grains',
          'Sugar & sweeteners', 'Oils'],
         "American-Chinese stir-fry of crispy flank steak in a sweet hoisin-soy glaze with scallions.",
         350, DL),

    # ────────────────────────── Vietnamese (small expansion) ──────────────
    meal('bo-luc-lac', 'Bò lúc lắc (shaking beef)', 'Vietnamese',
         ['Red meat', 'Other vegetables', 'Sauces', 'Oils',
          'Peppers & nightshades', 'Fresh herbs', 'Salt & seasonings'],
         "Wok-tossed beef cubes over watercress and tomato with a peppery lime sauce.",
         320, DL),
    meal('canh-chua-vietnamese', 'Canh chua', 'Vietnamese',
         ['White fish', 'Tropical fruits', 'Other vegetables',
          'Prepared soups & broths', 'Fresh herbs', 'Peppers & nightshades'],
         "Vietnamese sweet-and-sour fish soup with pineapple, tamarind, and bean sprouts.",
         400, DL),

    # ────────────────────────── South Asia regional expansion ─────────────
    meal('uttapam-south-indian', 'Uttapam', 'Indian-South',
         ['Whole grains', 'Legumes', 'Peppers & nightshades', 'Other vegetables',
          'Ground spices', 'Oils', 'Sauces'],
         "Thick, savory South Indian pancake of fermented rice-lentil batter topped with onions, peppers, and cilantro.",
         220, BRK),
    meal('avial-south-indian', 'Avial', 'Indian-South',
         ['Other vegetables', 'Yogurt', 'Plant milks', 'Whole spices',
          'Ground spices', 'Fresh herbs', 'Refined grains'],
         "South Indian coconut-yogurt vegetable curry — a Kerala onam classic.",
         300, DL),
    meal('chettinad-chicken', 'Chettinad chicken curry', 'Indian-South',
         ['Poultry', 'Whole spices', 'Ground spices', 'Plant milks',
          'Peppers & nightshades', 'Fresh herbs', 'Oils'],
         "Tamil Nadu's fiery Chettinad chicken in a roasted-spice, black-pepper, and coconut gravy.",
         400, DL),
    meal('puttu-kadala', 'Puttu and kadala curry', 'Indian-South',
         ['Whole grains', 'Plant milks', 'Legumes', 'Ground spices',
          'Whole spices', 'Other vegetables'],
         "Kerala steamed rice-and-coconut cylinders with a black-chickpea coconut curry — classic breakfast pairing.",
         350, BRK),

    # ────────────────────────── Sri Lankan expansion ──────────────────────
    meal('parippu-curry', 'Parippu (Sri Lankan dal)', 'Sri Lankan',
         ['Legumes', 'Plant milks', 'Ground spices', 'Whole spices',
          'Other vegetables', 'Oils'],
         "Red lentils cooked in coconut milk with mustard seeds, fenugreek, and curry leaves.",
         300, DL),
    meal('lamprais-sri-lankan', 'Lamprais', 'Sri Lankan',
         ['Refined grains', 'Red meat', 'Legumes', 'Other vegetables',
          'Ground spices', 'Eggs', 'Oils'],
         "Banana-leaf-wrapped Dutch-Burgher rice with a mixed-meat curry, frikkadel meatballs, and seeni sambol.",
         400, DL),

    # ────────────────────────── Africa: Egypt, Ethiopia, South Africa ─────
    meal('molokhia-egyptian', 'Molokhia', 'Egyptian',
         ['Leafy greens', 'Poultry', 'Prepared soups & broths', 'Whole spices',
          'Oils', 'Refined grains'],
         "Egyptian jute-mallow soup, finished with garlic-cilantro tarka and served over rice with rabbit or chicken.",
         400, DL),
    meal('hawawshi-egyptian', 'Hawawshi', 'Egyptian',
         ['Bread & rolls', 'Red meat', 'Other vegetables', 'Peppers & nightshades',
          'Fresh herbs', 'Ground spices'],
         "Spiced minced meat stuffed inside Egyptian baladi bread and toasted until charred and crispy.",
         300, DL),
    meal('injera-tibs', 'Injera with beef tibs', 'Ethiopian',
         ['Bread & rolls', 'Red meat', 'Peppers & nightshades', 'Spice blends',
          'Other vegetables', 'Oils'],
         "Spongy teff flatbread with sautéed cubes of beef seasoned in berbere spice.",
         400, DL),
    meal('shiro-ethiopian', 'Shiro wat', 'Ethiopian',
         ['Legumes', 'Spice blends', 'Oils', 'Peppers & nightshades',
          'Other vegetables', 'Bread & rolls'],
         "Creamy chickpea-flour stew spiced with berbere — fasting-day staple, eaten with injera.",
         300, DL),
    meal('boerewors-roll', 'Boerewors roll', 'South African',
         ['Processed meat', 'Bread & rolls', 'Other vegetables', 'Sauces',
          'Peppers & nightshades'],
         "South African coiled farmer\'s sausage in a long roll with chakalaka and tomato relish.",
         300, DL),
    meal('bobotie-south-african', 'Bobotie variations', 'South African',
         ['Red meat', 'Eggs', 'Dried fruits', 'Ground spices',
          'Spice blends', 'Bread & rolls', 'Milk'],
         "Cape Malay spiced minced beef baked with a savory egg-milk custard topping.",
         350, DL),

    # ────────────────────────── Brazilian / Latin expansion ───────────────
    meal('moqueca-baiana-brazilian', 'Moqueca baiana', 'Brazilian-Bahian',
         ['White fish', 'Plant milks', 'Peppers & nightshades', 'Other vegetables',
          'Oils', 'Fresh herbs', 'Citrus'],
         "Bahian fish stew in dendê palm oil, coconut milk, and peppers — Brazil's coastal Sunday lunch.",
         400, DL),
    meal('coxinha-brazilian', 'Coxinha', 'Brazilian',
         ['Poultry', 'Flours', 'Eggs', 'Oils',
          'Cream & butter', 'Salt & seasonings'],
         "Teardrop-shaped fried dough pouches filled with shredded chicken and cream cheese.",
         150, SNK),
    meal('pao-de-acai', 'Açaí bowl (Brazilian)', 'Brazilian',
         ['Berries', 'Tropical fruits', 'Whole grains', 'Nuts',
          'Sugar & sweeteners'],
         "Whipped frozen açaí pulp topped with granola, banana, and honey.",
         400, BRK),

    # ────────────────────────── Tex-Mex / American-Southern ───────────────
    meal('beef-nachos-texmex', 'Beef nachos', 'Tex-Mex',
         ['Baked snacks & pastries', 'Red meat', 'Processed cheese', 'Legumes',
          'Peppers & nightshades', 'Sauces', 'Fresh herbs'],
         "Tortilla chips loaded with ground beef, melted cheese, pickled jalapeños, and pico.",
         320, DL),
    meal('shrimp-and-grits', 'Shrimp and grits', 'American-Southern',
         ['Whole grains', 'Shellfish', 'Processed meat', 'Cream & butter',
          'Aged cheese', 'Other vegetables', 'Peppers & nightshades'],
         "Lowcountry stone-ground grits topped with bacon-and-andouille shrimp gravy.",
         350, DL, contains=['pork']),
    meal('fried-chicken-southern', 'Southern fried chicken', 'American-Southern',
         ['Poultry', 'Flours', 'Eggs', 'Oils',
          'Spice blends', 'Milk', 'Salt & seasonings'],
         "Buttermilk-brined chicken dredged in seasoned flour and pan-fried in cast iron.",
         320, DL),

    # ────────────────────────── Levantine / Iranian rounding ──────────────
    meal('abgoosht-iranian', 'Abgoosht (dizi)', 'Iranian',
         ['Red meat', 'Legumes', 'Starchy vegetables', 'Other vegetables',
          'Ground spices', 'Prepared soups & broths', 'Citrus'],
         "Iranian lamb-and-chickpea broth — diners mash the solids into a thick paste eaten with flatbread.",
         400, DL),
    meal('joojeh-kabab', 'Joojeh kabab', 'Iranian',
         ['Poultry', 'Yogurt', 'Citrus', 'Ground spices',
          'Refined grains', 'Cream & butter', 'Salt & seasonings'],
         "Saffron-yogurt marinated chicken skewers grilled over coals, served with buttered saffron rice.",
         400, DL),
]


def main():
    with PATH.open(encoding='utf-8') as f:
        meals = json.load(f)
    by_id = {m['id']: m for m in meals}

    added = 0
    collided = 0
    for new in NEW_MEALS:
        if new['id'] in by_id:
            collided += 1
            continue
        meals.append(new)
        added += 1

    with PATH.open('w', encoding='utf-8') as f:
        json.dump(meals, f, ensure_ascii=False, indent=2)
        f.write('\n')

    print(f'meals.json now contains {len(meals)} curated meals.')
    print(f'  added:    {added}')
    print(f'  collided: {collided}')


if __name__ == '__main__':
    main()
