#!/usr/bin/env python3
"""Round-2 curated-meal additions: deepen thin cuisines and add missing
ones outright.

Targets cuisines still under ~6-8 meals after round 1, plus a handful
that weren't represented at all (Israeli, Jewish-Ashkenazi, Czech,
Romanian, Burmese, Nepali, Cambodian, Lao, Hawaiian, Native American).

Each entry carries realistic ingredient_categories, tags, serving_grams,
and contains markers for pork / alcohol where the dish is genuinely
defined by it (e.g. carnitas, kalua pig, schweinshaxe). After this
runs, re-derive diet_compatibility via the existing script.

Run from project root:
    python scripts/add_curated_meals_v2.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PATH = ROOT / 'src' / 'data' / 'meals.json'

DL = ('dinner', 'lunch')
DESS = ('dessert',)
BRK = ('breakfast',)
SNK = ('snack',)
BL = ('breakfast', 'lunch')
LSN = ('lunch', 'snack')


def m(id, name, cuisine, cats, notes, serving_grams, tags=DL, contains=None):
    rec = {
        'id': id,
        'name': name,
        'ingredient_categories': list(cats),
        'notes': notes,
        'cuisine': cuisine,
        'frequency': 1,
        'source': 'curated',
        'tags': list(tags),
        'serving_grams': serving_grams,
    }
    if contains:
        rec['contains'] = sorted(set(contains))
    return rec


NEW = [
    # ════════════════════════ SPANISH (8 → 14) ═════════════════════════
    m('fabada-asturiana', 'Fabada asturiana', 'Spanish',
      ['Legumes', 'Processed meat', 'Red meat', 'Ground spices', 'Oils', 'Salt & seasonings'],
      "Asturian white-bean stew with chorizo, morcilla, and pork shoulder — slow-cooked to a thick, smoky pot.",
      400, DL, contains=['pork']),
    m('migas-spanish', 'Migas extremeñas', 'Spanish',
      ['Bread & rolls', 'Processed meat', 'Eggs', 'Peppers & nightshades', 'Oils', 'Other vegetables'],
      "Day-old bread cubes fried with chorizo, garlic, and peppers — a shepherd's breakfast.",
      280, BL, contains=['pork']),
    m('cocido-madrileno', 'Cocido madrileño', 'Spanish',
      ['Legumes', 'Red meat', 'Processed meat', 'Other vegetables', 'Starchy vegetables', 'Refined grains'],
      "Madrid's three-course chickpea boil — broth with noodles, then chickpeas with vegetables, then the meats.",
      450, DL, contains=['pork']),
    m('pisto-manchego', 'Pisto manchego', 'Spanish',
      ['Peppers & nightshades', 'Other vegetables', 'Oils', 'Eggs', 'Salt & seasonings'],
      "La Mancha's slow-cooked summer vegetable stew of zucchini, tomato, and peppers, topped with a fried egg.",
      320, DL),
    m('croquetas-de-jamon', 'Croquetas de jamón', 'Spanish',
      ['Flours', 'Milk', 'Processed meat', 'Eggs', 'Bread & rolls', 'Oils'],
      "Crisp panko-coated bites of jamón-laced béchamel, the king of Spanish tapas.",
      150, LSN, contains=['pork']),
    m('escalivada', 'Escalivada', 'Spanish',
      ['Peppers & nightshades', 'Other vegetables', 'Oils', 'Salt & seasonings', 'Bread & rolls'],
      "Catalan smoke-roasted peppers, eggplant, and onion peeled and drizzled with olive oil.",
      250, DL),
    m('rabo-de-toro', 'Rabo de toro', 'Spanish',
      ['Red meat', 'Other vegetables', 'Alcoholic beverages', 'Whole spices', 'Starchy vegetables', 'Oils'],
      "Andalusian oxtail braised in red wine until the meat slides off the bone.",
      400, DL),

    # ════════════════════════ PORTUGUESE (3 → 10) ═══════════════════════
    m('bacalhau-a-bras', 'Bacalhau à brás', 'Portuguese',
      ['Canned & cured fish', 'Starchy vegetables', 'Eggs', 'Other vegetables', 'Oils', 'Pickled vegetables'],
      "Salt cod scrambled with shredded potatoes and eggs, finished with black olives and parsley.",
      350, DL),
    m('francesinha', 'Francesinha', 'Portuguese',
      ['Bread & rolls', 'Red meat', 'Processed meat', 'Aged cheese', 'Sauces', 'Eggs'],
      "Porto's monster sandwich — steak, ham, sausage, cheese, drowned in a beer-tomato sauce, topped with a fried egg.",
      450, DL, contains=['pork', 'alcohol']),
    m('cataplana-portuguesa', 'Cataplana de marisco', 'Portuguese',
      ['Shellfish', 'White fish', 'Peppers & nightshades', 'Other vegetables', 'Alcoholic beverages', 'Oils'],
      "Algarve's clam-and-shrimp stew steamed in a copper cataplana with white wine and cilantro.",
      400, DL, contains=['alcohol']),
    m('arroz-de-marisco', 'Arroz de marisco', 'Portuguese',
      ['Refined grains', 'Shellfish', 'White fish', 'Peppers & nightshades', 'Other vegetables', 'Oils'],
      "Soupy seafood rice — Portuguese coastal Sunday lunch.",
      450, DL),
    m('sardinhas-assadas', 'Sardinhas assadas', 'Portuguese',
      ['Oily fish', 'Bread & rolls', 'Peppers & nightshades', 'Other vegetables', 'Oils', 'Salt & seasonings'],
      "Charcoal-grilled fresh sardines on rustic bread with a salad of peppers and onion — Lisbon's June feast.",
      280, DL),
    m('pastel-de-nata', 'Pastel de nata', 'Portuguese',
      ['Baked snacks & pastries', 'Eggs', 'Sugar & sweeteners', 'Milk', 'Flours', 'Cream & butter'],
      "Lisbon's iconic custard tart with a flaky puff-pastry shell, scorched on top.",
      80, DESS),
    m('caldeirada-portuguesa', 'Caldeirada de peixe', 'Portuguese',
      ['White fish', 'Shellfish', 'Starchy vegetables', 'Peppers & nightshades', 'Other vegetables', 'Oils'],
      "Portuguese fisherman's stew — layered fish, potato, tomato, and bay leaf in a shallow pot.",
      380, DL),

    # ════════════════════════ GREEK (7 → 12) ════════════════════════════
    m('avgolemono-soup', 'Avgolemono soup', 'Greek',
      ['Refined grains', 'Poultry', 'Eggs', 'Citrus', 'Prepared soups & broths', 'Salt & seasonings'],
      "Greek lemon-egg chicken soup with orzo — luscious and tart, perfect when you're sick.",
      350, DL),
    m('dolmades', 'Dolmades (stuffed grape leaves)', 'Greek',
      ['Leafy greens', 'Refined grains', 'Fresh herbs', 'Citrus', 'Oils', 'Pickled vegetables'],
      "Grape leaves rolled around lemony rice with dill and mint — cold or warm.",
      220, LSN),
    m('saganaki', 'Saganaki', 'Greek',
      ['Aged cheese', 'Flours', 'Oils', 'Citrus', 'Salt & seasonings'],
      "Pan-fried slab of kefalotyri or graviera cheese, finished with a squeeze of lemon and sometimes flamed in ouzo.",
      180, DL),
    m('keftedes', 'Keftedes', 'Greek',
      ['Red meat', 'Bread & rolls', 'Eggs', 'Fresh herbs', 'Salt & seasonings', 'Oils', 'Other vegetables'],
      "Greek meatballs flavored with mint, oregano, and grated onion — pan-fried until crusty.",
      300, DL),
    m('fasolada', 'Fasolada', 'Greek',
      ['Legumes', 'Other vegetables', 'Peppers & nightshades', 'Oils', 'Fresh herbs', 'Salt & seasonings'],
      "Greek navy-bean soup, considered the national dish — thick, tomatoey, and olive-oil-rich.",
      350, DL),

    # ════════════════════════ RUSSIAN (4 → 9) ═══════════════════════════
    m('shchi-russian', 'Shchi (cabbage soup)', 'Russian',
      ['Leafy greens', 'Other vegetables', 'Red meat', 'Starchy vegetables', 'Fermented dairy', 'Fresh herbs'],
      "Russian sour cabbage soup with beef and potato, served with smetana and rye bread.",
      350, DL),
    m('vinaigrette-russian', 'Vinegret', 'Russian',
      ['Starchy vegetables', 'Other vegetables', 'Pickled vegetables', 'Legumes', 'Oils', 'Salt & seasonings'],
      "Russian beet salad with boiled potatoes, carrots, sauerkraut, and peas, dressed in sunflower oil.",
      250, LSN),
    m('syrniki', 'Syrniki', 'Russian',
      ['Fresh cheese', 'Eggs', 'Flours', 'Sugar & sweeteners', 'Cream & butter', 'Berries'],
      "Russian quark-cheese pancakes, golden-fried and served with smetana and jam.",
      200, BRK),
    m('medovik-cake', 'Medovik (honey cake)', 'Russian',
      ['Flours', 'Eggs', 'Sugar & sweeteners', 'Cream & butter', 'Fermented dairy', 'Jams & preserves'],
      "Layered Russian honey cake softened by overnight rest in a sour-cream frosting.",
      150, DESS),
    m('beef-tongue-salad-russian', 'Tongue salad with horseradish', 'Russian',
      ['Organ meats', 'Other vegetables', 'Fresh herbs', 'Sauces', 'Oils', 'Salt & seasonings'],
      "Tender boiled beef tongue with pickle, parsley, and a horseradish-mustard dressing — Soviet zakuski staple.",
      220, LSN),

    # ════════════════════════ POLISH (4 → 9) ═══════════════════════════
    m('golabki-polish', 'Gołąbki', 'Polish',
      ['Leafy greens', 'Refined grains', 'Red meat', 'Other vegetables', 'Sauces', 'Salt & seasonings'],
      "Polish cabbage rolls stuffed with pork-and-rice, simmered in tomato sauce.",
      350, DL, contains=['pork']),
    m('mizeria-cucumber-salad', 'Mizeria', 'Polish',
      ['Other vegetables', 'Fermented dairy', 'Sugar & sweeteners', 'Fresh herbs', 'Salt & seasonings'],
      "Polish cucumber-and-sour-cream salad with dill — summer side staple.",
      150, LSN),
    m('makowiec', 'Makowiec', 'Polish',
      ['Flours', 'Seeds', 'Eggs', 'Sugar & sweeteners', 'Dried fruits', 'Cream & butter'],
      "Polish poppy-seed roll — yeasted dough spiraled around a sweetened poppy-seed filling.",
      130, DESS),
    m('placki-ziemniaczane', 'Placki ziemniaczane', 'Polish',
      ['Starchy vegetables', 'Eggs', 'Flours', 'Oils', 'Fermented dairy', 'Salt & seasonings'],
      "Polish potato pancakes pan-fried to a golden crust, served with sour cream or apple sauce.",
      220, BL),
    m('sernik-polish', 'Sernik', 'Polish',
      ['Fresh cheese', 'Eggs', 'Sugar & sweeteners', 'Flours', 'Cream & butter', 'Baked snacks & pastries'],
      "Polish twaróg cheesecake — denser and less sweet than the New York version.",
      140, DESS),

    # ════════════════════════ HUNGARIAN (3 → 8) ════════════════════════
    m('halaszle-hungarian', 'Halászlé', 'Hungarian',
      ['Freshwater fish', 'Peppers & nightshades', 'Other vegetables', 'Ground spices', 'Prepared soups & broths', 'Oils'],
      "Hungarian river-fish soup — fiery paprika broth with chunks of carp and pike.",
      400, DL),
    m('langos', 'Lángos', 'Hungarian',
      ['Flours', 'Oils', 'Aged cheese', 'Fermented dairy', 'Other vegetables', 'Salt & seasonings'],
      "Hungarian deep-fried flatbread topped with garlic oil, sour cream, and grated cheese.",
      220, LSN),
    m('toltott-kaposzta', 'Töltött káposzta', 'Hungarian',
      ['Pickled vegetables', 'Red meat', 'Refined grains', 'Processed meat', 'Sauces', 'Ground spices'],
      "Hungarian sauerkraut cabbage rolls with pork, rice, and smoked sausage in paprika broth.",
      380, DL, contains=['pork']),
    m('paprikas-krumpli', 'Paprikás krumpli', 'Hungarian',
      ['Starchy vegetables', 'Processed meat', 'Peppers & nightshades', 'Ground spices', 'Oils', 'Fresh herbs'],
      "Hungarian potato paprikash with sausage — peasant stew, dark with sweet paprika.",
      350, DL, contains=['pork']),
    m('dobos-torta', 'Dobos torta', 'Hungarian',
      ['Flours', 'Eggs', 'Sugar & sweeteners', 'Candy & desserts', 'Cream & butter', 'Baking ingredients'],
      "Hungarian seven-layer sponge cake with chocolate buttercream and a brittle caramel cap.",
      140, DESS),

    # ════════════════════════ GERMAN (5 → 10) ══════════════════════════
    m('schweinshaxe', 'Schweinshaxe', 'German',
      ['Red meat', 'Pickled vegetables', 'Starchy vegetables', 'Alcoholic beverages', 'Whole spices', 'Salt & seasonings'],
      "Bavarian roasted pork knuckle with crackling crust, served with sauerkraut and a dumpling.",
      400, DL, contains=['pork']),
    m('rouladen-german', 'Rinderrouladen', 'German',
      ['Red meat', 'Processed meat', 'Pickled vegetables', 'Other vegetables', 'Sauces', 'Whole spices'],
      "German beef rolls stuffed with bacon, pickle, and onion, braised in a dark gravy.",
      380, DL, contains=['pork']),
    m('flammkuchen', 'Flammkuchen', 'German',
      ['Flours', 'Processed meat', 'Fermented dairy', 'Other vegetables', 'Oils', 'Salt & seasonings'],
      "Alsatian thin tart topped with crème fraîche, lardons, and onion, baked until crisp.",
      280, DL, contains=['pork']),
    m('eintopf-german', 'Linseneintopf', 'German',
      ['Legumes', 'Processed meat', 'Other vegetables', 'Starchy vegetables', 'Salt & seasonings', 'Whole spices'],
      "German lentil one-pot with sausage, carrots, and potatoes — winter Hausmannskost.",
      400, DL, contains=['pork']),
    m('apfelstrudel', 'Apfelstrudel', 'German',
      ['Temperate fruits', 'Flours', 'Sugar & sweeteners', 'Cream & butter', 'Nuts', 'Ground spices'],
      "Layered phyllo wrapped around sugared apples, raisins, and walnuts; dusted with sugar.",
      150, DESS),

    # ════════════════════════ AUSTRIAN (1 → 4) ═════════════════════════
    m('kaiserschmarrn', 'Kaiserschmarrn', 'Austrian',
      ['Flours', 'Eggs', 'Milk', 'Sugar & sweeteners', 'Cream & butter', 'Dried fruits', 'Jams & preserves'],
      "Austrian shredded pancake with raisins, dusted with powdered sugar and served with plum compote.",
      220, DESS),
    m('wiener-frankfurter', 'Wiener Würstel with mustard', 'Austrian',
      ['Processed meat', 'Bread & rolls', 'Sauces', 'Pickled vegetables', 'Salt & seasonings'],
      "Vienna's classic frankfurter pair served with crusty Semmel rolls and Estragon mustard.",
      250, DL, contains=['pork']),
    m('viennese-goulash', 'Wiener Saftgulasch', 'Austrian',
      ['Red meat', 'Ground spices', 'Other vegetables', 'Sauces', 'Bread & rolls', 'Oils'],
      "Vienna's beef goulash — onion-heavy, deeply paprikaed, served with a kaiser roll for dunking.",
      400, DL),

    # ════════════════════════ CZECH (0 → 4) ════════════════════════════
    m('svickova-na-smetane', 'Svíčková na smetaně', 'Czech',
      ['Red meat', 'Other vegetables', 'Sauces', 'Fermented dairy', 'Sugar & sweeteners', 'Berries', 'Bread & rolls'],
      "Czech beef sirloin in a velvety root-vegetable cream sauce, served with bread dumplings and cranberry.",
      400, DL),
    m('vepro-knedlo-zelo', 'Vepřo-knedlo-zelo', 'Czech',
      ['Red meat', 'Bread & rolls', 'Pickled vegetables', 'Sauces', 'Whole spices', 'Salt & seasonings'],
      "Roast pork with bread dumplings and braised sauerkraut — Bohemian Sunday lunch.",
      420, DL, contains=['pork']),
    m('smazeny-syr', 'Smažený sýr', 'Czech',
      ['Aged cheese', 'Flours', 'Eggs', 'Bread & rolls', 'Oils', 'Sauces', 'Starchy vegetables'],
      "Czech fried cheese — slab of Edam-style cheese breaded and pan-fried, served with fries and tartar sauce.",
      280, DL),
    m('halusky-czech', 'Halušky s bryndzou', 'Czech',
      ['Flours', 'Starchy vegetables', 'Fresh cheese', 'Processed meat', 'Cream & butter', 'Fermented dairy'],
      "Slovak-Czech potato dumplings with sheep cheese and crispy bacon.",
      350, DL, contains=['pork']),

    # ════════════════════════ ROMANIAN (0 → 4) ═════════════════════════
    m('sarmale-romanian', 'Sarmale', 'Romanian',
      ['Pickled vegetables', 'Red meat', 'Refined grains', 'Processed meat', 'Sauces', 'Whole spices', 'Fermented dairy'],
      "Romanian sauerkraut-leaf rolls with pork and rice, simmered for hours and served with mămăligă and sour cream.",
      350, DL, contains=['pork']),
    m('mititei', 'Mititei', 'Romanian',
      ['Red meat', 'Ground spices', 'Whole spices', 'Bread & rolls', 'Sauces', 'Salt & seasonings'],
      "Romanian skinless garlic-and-allspice grilled sausages — the king of the Bucharest beer garden.",
      250, DL),
    m('mamaliga-romanian', 'Mămăligă cu brânză', 'Romanian',
      ['Whole grains', 'Fresh cheese', 'Cream & butter', 'Eggs', 'Salt & seasonings'],
      "Romanian polenta layered with sheep cheese and topped with a fried egg.",
      300, DL),
    m('ciorba-de-burta', 'Ciorbă de burtă', 'Romanian',
      ['Organ meats', 'Prepared soups & broths', 'Fermented dairy', 'Whole spices', 'Other vegetables', 'Peppers & nightshades'],
      "Romanian tripe sour soup — pearly white from the egg-yolk-and-cream finish, sharpened with vinegar and garlic.",
      350, DL),

    # ════════════════════════ JEWISH-ASHKENAZI (0 → 5) ═════════════════
    m('matzo-ball-soup', 'Matzo ball soup', 'Jewish-Ashkenazi',
      ['Bread & rolls', 'Eggs', 'Cream & butter', 'Poultry', 'Prepared soups & broths', 'Fresh herbs', 'Other vegetables'],
      "Schmaltz-rich knaidlach in a clear chicken broth with carrots and dill — Friday night staple.",
      400, DL),
    m('brisket-jewish', 'Braised brisket', 'Jewish-Ashkenazi',
      ['Red meat', 'Other vegetables', 'Sauces', 'Sugar & sweeteners', 'Whole spices', 'Starchy vegetables'],
      "Slow-braised beef brisket with onions, prunes, and a tangy ketchup-Coca-Cola sauce — Passover and Hanukkah standard.",
      380, DL),
    m('latkes', 'Latkes', 'Jewish-Ashkenazi',
      ['Starchy vegetables', 'Eggs', 'Flours', 'Oils', 'Salt & seasonings', 'Sauces', 'Temperate fruits'],
      "Crispy potato pancakes with apple sauce and sour cream — Hanukkah miracle of oil.",
      200, LSN),
    m('challah-bread', 'Challah', 'Jewish-Ashkenazi',
      ['Flours', 'Eggs', 'Sugar & sweeteners', 'Oils', 'Salt & seasonings'],
      "Braided egg-enriched Shabbat bread — slightly sweet, golden-domed from an egg-wash.",
      80, LSN),
    m('noodle-kugel', 'Noodle kugel', 'Jewish-Ashkenazi',
      ['Refined grains', 'Eggs', 'Cream & butter', 'Sugar & sweeteners', 'Fresh cheese', 'Dried fruits', 'Ground spices'],
      "Sweet baked noodle pudding with cottage cheese, raisins, and cinnamon — Ashkenazi holiday side.",
      250, DL),

    # ════════════════════════ ISRAELI (0 → 6) ══════════════════════════
    m('sabich-israeli', 'Sabich', 'Israeli',
      ['Bread & rolls', 'Other vegetables', 'Eggs', 'Legumes', 'Sauces', 'Pickled vegetables', 'Fresh herbs'],
      "Iraqi-Jewish pita stuffed with fried eggplant, hard-boiled egg, hummus, amba mango sauce, and tabbouleh.",
      280, DL),
    m('israeli-shakshuka', 'Shakshuka (Israeli-style)', 'Israeli',
      ['Eggs', 'Peppers & nightshades', 'Other vegetables', 'Fresh cheese', 'Bread & rolls', 'Fresh herbs', 'Oils'],
      "Eggs poached in a thick pepper-tomato sauce, crumbled with feta and scooped with pita.",
      350, BL),
    m('jachnun-yemenite', 'Jachnun', 'Israeli',
      ['Flours', 'Cream & butter', 'Sauces', 'Peppers & nightshades', 'Eggs'],
      "Slow-baked Yemenite-Jewish rolled pastry, served with grated tomato and zhug for Shabbat morning.",
      180, BRK),
    m('israeli-couscous-salad', 'Israeli couscous salad', 'Israeli',
      ['Refined grains', 'Other vegetables', 'Peppers & nightshades', 'Fresh herbs', 'Oils', 'Citrus', 'Nuts'],
      "Toasted pearl couscous tossed with chopped vegetables, parsley, lemon, and olive oil.",
      300, DL),
    m('falafel-israeli', 'Falafel pita', 'Israeli',
      ['Legumes', 'Bread & rolls', 'Other vegetables', 'Sauces', 'Pickled vegetables', 'Fresh herbs', 'Oils'],
      "Crisp chickpea fritters stuffed in pita with salads, pickles, tahini, and amba.",
      300, DL),
    m('malabi-israeli', 'Malabi', 'Israeli',
      ['Milk', 'Sugar & sweeteners', 'Extracts & essences', 'Nuts', 'Berries'],
      "Rose-water-perfumed milk pudding with a ruby raspberry syrup and crushed pistachios.",
      150, DESS),

    # ════════════════════════ INDONESIAN (4 → 9) ═══════════════════════
    m('soto-ayam', 'Soto ayam', 'Indonesian',
      ['Poultry', 'Refined grains', 'Prepared soups & broths', 'Whole spices', 'Fresh herbs', 'Citrus', 'Eggs'],
      "Indonesian turmeric chicken soup with vermicelli, hard-boiled egg, and a side of sambal.",
      400, DL),
    m('nasi-uduk', 'Nasi uduk', 'Indonesian',
      ['Refined grains', 'Plant milks', 'Whole spices', 'Eggs', 'Poultry', 'Peppers & nightshades'],
      "Jakartan coconut rice served with fried chicken, omelet ribbons, fried shallots, and sambal.",
      400, BRK),
    m('rendang-padang-2', 'Rendang padang (Minangkabau)', 'Indonesian',
      ['Red meat', 'Plant milks', 'Ground spices', 'Peppers & nightshades', 'Fresh herbs', 'Whole spices'],
      "West-Sumatran dry beef rendang — meat braised until the coconut milk caramelizes into a black, fragrant crust.",
      300, DL),
    m('bakso-indonesian', 'Bakso', 'Indonesian',
      ['Red meat', 'Refined grains', 'Prepared soups & broths', 'Other vegetables', 'Sauces', 'Fresh herbs'],
      "Indonesian beef meatball noodle soup, ubiquitous from street carts to malls.",
      400, DL),
    m('pempek-indonesian', 'Pempek', 'Indonesian',
      ['White fish', 'Flours', 'Eggs', 'Sauces', 'Peppers & nightshades'],
      "Palembang fish cakes served with a tangy-spicy vinegar sauce called kuah cuko.",
      220, DL),

    # ════════════════════════ MALAY (2 → 6) ════════════════════════════
    m('nasi-lemak', 'Nasi lemak', 'Malay',
      ['Refined grains', 'Plant milks', 'Canned & cured fish', 'Eggs', 'Nuts', 'Peppers & nightshades', 'Other vegetables'],
      "Malaysia's national breakfast — coconut rice with sambal ikan bilis, hard-boiled egg, peanuts, cucumber, and fried anchovies.",
      350, BRK),
    m('char-kway-teow', 'Char kway teow', 'Malay',
      ['Refined grains', 'Shellfish', 'Eggs', 'Other vegetables', 'Sauces', 'Oils', 'Processed meat'],
      "Wok-charred flat rice noodles with prawns, lap cheong, bean sprouts, and a dark sweet-soy.",
      350, DL, contains=['pork']),
    m('roti-canai', 'Roti canai with dal', 'Malay',
      ['Flours', 'Cream & butter', 'Legumes', 'Ground spices', 'Oils'],
      "Flaky, layered flatbread tossed at the griddle and served with a thin lentil dhal for dipping.",
      280, BL),
    m('asam-laksa', 'Asam laksa (Penang)', 'Malay',
      ['Refined grains', 'Oily fish', 'Pastes & ferments', 'Tropical fruits', 'Peppers & nightshades', 'Fresh herbs'],
      "Penang's sour mackerel-broth noodle soup with pineapple, mint, and torch ginger.",
      400, DL),

    # ════════════════════════ VIETNAMESE (8 → 12) ══════════════════════
    m('banh-xeo-vietnamese', 'Bánh xèo', 'Vietnamese',
      ['Flours', 'Plant milks', 'Shellfish', 'Red meat', 'Other vegetables', 'Fresh herbs', 'Sauces'],
      "Sizzling turmeric crepe stuffed with shrimp, pork, and bean sprouts — wrapped in lettuce with herbs and nước chấm.",
      300, DL, contains=['pork']),
    m('ca-kho-to', 'Cá kho tộ', 'Vietnamese',
      ['White fish', 'Refined grains', 'Sauces', 'Sugar & sweeteners', 'Peppers & nightshades', 'Fresh herbs'],
      "Vietnamese clay-pot catfish caramelized in a salty-sweet fish-sauce and palm-sugar glaze.",
      350, DL),
    m('bun-rieu-vietnamese', 'Bún riêu cua', 'Vietnamese',
      ['Refined grains', 'Shellfish', 'Eggs', 'Pastes & ferments', 'Tropical fruits', 'Prepared soups & broths', 'Fresh herbs'],
      "Northern Vietnamese crab-paste vermicelli soup — bright red broth with tomato, tofu, and shrimp paste.",
      450, DL),
    m('xoi-vietnamese', 'Xôi mặn', 'Vietnamese',
      ['Refined grains', 'Processed meat', 'Eggs', 'Peppers & nightshades', 'Oils'],
      "Vietnamese sticky rice topped with Chinese sausage, fried shallot, mung bean, and shredded chicken floss.",
      280, BRK, contains=['pork']),

    # ════════════════════════ THAI (8 → 12) ════════════════════════════
    m('khao-pad-thai', 'Khao pad (Thai fried rice)', 'Thai',
      ['Refined grains', 'Poultry', 'Eggs', 'Other vegetables', 'Sauces', 'Citrus', 'Fresh herbs'],
      "Thai jasmine fried rice with chicken, egg, garlic, and a squeeze of lime — paired with cucumber and Sriracha.",
      400, DL),
    m('khao-niew-mamuang', 'Khao niew mamuang', 'Thai',
      ['Refined grains', 'Tropical fruits', 'Plant milks', 'Sugar & sweeteners', 'Seeds', 'Salt & seasonings'],
      "Thai sticky rice soaked in salted coconut cream, served with ripe mango and toasted sesame.",
      280, DESS),
    m('panang-curry', 'Panang curry beef', 'Thai',
      ['Red meat', 'Pastes & ferments', 'Plant milks', 'Peppers & nightshades', 'Fresh herbs', 'Refined grains', 'Nuts'],
      "Drier, peanut-thickened Thai curry over rice with kaffir lime leaves and Thai basil.",
      400, DL),
    m('khao-mun-gai', 'Khao mun gai', 'Thai',
      ['Poultry', 'Refined grains', 'Sauces', 'Other vegetables', 'Pastes & ferments', 'Fresh herbs'],
      "Thai Hainanese chicken rice — poached chicken over garlicky chicken-fat rice with ginger-soy sauce.",
      400, DL),

    # ════════════════════════ KOREAN (8 → 12) ══════════════════════════
    m('jjajangmyeon-korean', 'Jjajangmyeon', 'Korean',
      ['Refined grains', 'Red meat', 'Other vegetables', 'Pastes & ferments', 'Oils', 'Starchy vegetables'],
      "Korean-Chinese noodles in a black-bean sauce with diced pork and onion.",
      400, DL, contains=['pork']),
    m('bossam-korean', 'Bossam', 'Korean',
      ['Red meat', 'Leafy greens', 'Pastes & ferments', 'Other vegetables', 'Pickled vegetables', 'Sauces'],
      "Korean boiled pork belly wrapped in lettuce or kimchi with raw garlic, fermented shrimp, and ssamjang.",
      400, DL, contains=['pork']),
    m('jeon-korean-pancakes', 'Pajeon (scallion pancake)', 'Korean',
      ['Other vegetables', 'Flours', 'Eggs', 'Shellfish', 'Sauces', 'Oils'],
      "Korean savory scallion pancake studded with shrimp and squid, served with a vinegar-soy dipping sauce.",
      250, DL),
    m('soondae', 'Soondae', 'Korean',
      ['Processed meat', 'Refined grains', 'Organ meats', 'Sauces', 'Other vegetables'],
      "Korean blood sausage of glass noodles and pig's blood, served with liver and a salt-pepper dip.",
      220, DL, contains=['pork']),

    # ════════════════════════ JAPANESE (17 → 22) ═══════════════════════
    m('chirashi-don', 'Chirashi don', 'Japanese',
      ['Refined grains', 'Oily fish', 'White fish', 'Shellfish', 'Eggs', 'Other vegetables', 'Pickled vegetables'],
      "Bowl of sushi rice scattered with sashimi-grade fish, salmon roe, and pickled vegetables.",
      400, DL),
    m('curry-rice-japanese', 'Japanese curry rice', 'Japanese',
      ['Refined grains', 'Red meat', 'Other vegetables', 'Sauces', 'Ground spices', 'Starchy vegetables', 'Oils'],
      "Thick, sweet brown Japanese curry over rice with chunks of beef, carrot, potato, and a crisp fukujinzuke pickle.",
      450, DL),
    m('yakitori-platter', 'Yakitori platter', 'Japanese',
      ['Poultry', 'Sauces', 'Other vegetables', 'Salt & seasonings', 'Oils'],
      "Skewered grilled chicken cuts brushed with tare or sprinkled with salt — thigh, breast, scallion, liver, gizzard.",
      300, DL),
    m('nikujaga', 'Nikujaga', 'Japanese',
      ['Red meat', 'Starchy vegetables', 'Other vegetables', 'Sauces', 'Sugar & sweeteners', 'Salt & seasonings'],
      "Japanese home-style beef-and-potato stew simmered in soy, mirin, and dashi.",
      380, DL),
    m('onigiri-set', 'Onigiri assortment', 'Japanese',
      ['Refined grains', 'Canned & cured fish', 'Oily fish', 'Pickled vegetables', 'Salt & seasonings', 'Seeds'],
      "Triangular rice balls wrapped in nori with assorted fillings: salmon, umeboshi, tuna mayo, kombu.",
      180, LSN),

    # ════════════════════════ TURKISH (10 → 14) ════════════════════════
    m('manti-turkish', 'Mantı', 'Turkish',
      ['Bread & rolls', 'Red meat', 'Yogurt', 'Sauces', 'Whole spices', 'Cream & butter'],
      "Tiny Turkish dumplings under garlic yogurt and a butter-paprika sauce.",
      300, DL),
    m('pide-turkish', 'Pide', 'Turkish',
      ['Bread & rolls', 'Aged cheese', 'Red meat', 'Eggs', 'Other vegetables', 'Peppers & nightshades'],
      "Boat-shaped Turkish flatbread with sucuk, cheese, and egg or spiced minced lamb.",
      300, DL),
    m('kuzu-tandir', 'Kuzu tandır', 'Turkish',
      ['Red meat', 'Refined grains', 'Whole spices', 'Other vegetables', 'Oils', 'Salt & seasonings'],
      "Anatolian slow-roasted lamb shoulder, fall-apart tender over saffron rice with pine nuts.",
      400, DL),
    m('cig-kofte', 'Çiğ köfte', 'Turkish',
      ['Whole grains', 'Peppers & nightshades', 'Fresh herbs', 'Citrus', 'Spice blends', 'Ground spices'],
      "Modern vegetarian Turkish bulgur 'tartare' kneaded with pepper paste and walnuts, wrapped in lettuce.",
      150, LSN),

    # ════════════════════════ LEVANTINE (12 → 17) ══════════════════════
    m('mansaf-jordanian', 'Mansaf', 'Levantine',
      ['Red meat', 'Yogurt', 'Refined grains', 'Bread & rolls', 'Nuts', 'Whole spices', 'Fresh herbs'],
      "Jordan's national dish — lamb in a hot fermented-yogurt sauce over rice and shrak bread, topped with toasted pine nuts.",
      450, DL),
    m('maqluba', 'Maqluba', 'Levantine',
      ['Refined grains', 'Poultry', 'Other vegetables', 'Peppers & nightshades', 'Whole spices', 'Oils', 'Nuts'],
      "Palestinian 'upside-down' rice pot — chicken and fried eggplant layered with spiced rice, flipped onto a platter.",
      400, DL),
    m('knafeh-levantine', 'Knafeh', 'Levantine',
      ['Baked snacks & pastries', 'Fresh cheese', 'Sugar & sweeteners', 'Nuts', 'Extracts & essences', 'Cream & butter'],
      "Shredded-phyllo cheese pastry soaked in rose-orange syrup and topped with pistachios — Nablus's specialty.",
      150, DESS),
    m('sambousek-levantine', 'Sambousek', 'Levantine',
      ['Baked snacks & pastries', 'Red meat', 'Fresh cheese', 'Ground spices', 'Oils', 'Fresh herbs'],
      "Crescent-shaped Levantine pies with spiced minced meat or salty cheese — fried or oven-baked.",
      180, LSN),
    m('makluba-shellfish', 'Maqluba bil samak', 'Levantine',
      ['Refined grains', 'White fish', 'Other vegetables', 'Peppers & nightshades', 'Whole spices', 'Nuts'],
      "Gaza-style fish maqluba with sea bass, cauliflower, and rice — flipped tableside with crispy bottom up.",
      400, DL),

    # ════════════════════════ IRANIAN (5 → 10) ═════════════════════════
    m('baghali-polo', 'Baghali polo ba mahiche', 'Iranian',
      ['Refined grains', 'Red meat', 'Legumes', 'Fresh herbs', 'Whole spices', 'Cream & butter'],
      "Persian dill-and-fava-bean rice with slow-braised lamb shank.",
      450, DL),
    m('kashk-e-bademjan', 'Kashk-e bademjan', 'Iranian',
      ['Other vegetables', 'Fermented dairy', 'Nuts', 'Oils', 'Whole spices', 'Fresh herbs'],
      "Persian mashed eggplant dip with kashk (whey-paste), caramelized onion, and saffron — eaten with sangak bread.",
      200, LSN),
    m('dizi-iranian', 'Dizi (abgoosht)', 'Iranian',
      ['Red meat', 'Legumes', 'Starchy vegetables', 'Other vegetables', 'Whole spices', 'Bread & rolls'],
      "Stone-pot lamb-and-chickpea stew — diners drain the broth, mash the solids, and eat both over flatbread.",
      400, DL),
    m('zereshk-polo', 'Zereshk polo ba morgh', 'Iranian',
      ['Refined grains', 'Poultry', 'Berries', 'Whole spices', 'Cream & butter', 'Sugar & sweeteners', 'Nuts'],
      "Persian saffron rice with tart barberries and caramelized onion-saffron chicken.",
      420, DL),

    # ════════════════════════ EGYPTIAN (5 → 9) ═════════════════════════
    m('mahshi-egyptian', 'Mahshi', 'Egyptian',
      ['Other vegetables', 'Refined grains', 'Red meat', 'Fresh herbs', 'Whole spices', 'Sauces'],
      "Egyptian stuffed zucchini, cabbage, and grape leaves in tomato broth — sometimes meatless for Lent.",
      350, DL),
    m('tameya', 'Ta\'meya (Egyptian falafel)', 'Egyptian',
      ['Legumes', 'Fresh herbs', 'Whole spices', 'Bread & rolls', 'Other vegetables', 'Sauces', 'Oils'],
      "Egypt's fava-bean falafel — green inside, fried crisp, stuffed in baladi bread with salad and tahina.",
      250, BL),
    m('om-ali-egyptian', 'Om Ali', 'Egyptian',
      ['Baked snacks & pastries', 'Milk', 'Cream & butter', 'Nuts', 'Dried fruits', 'Sugar & sweeteners'],
      "Egypt's bread-and-milk pudding with phyllo, pistachios, raisins, and coconut.",
      200, DESS),
    m('koshary-2', 'Koshary (vendor-style)', 'Egyptian',
      ['Refined grains', 'Legumes', 'Pasta & noodles' if False else 'Refined grains', 'Sauces', 'Other vegetables', 'Peppers & nightshades'],
      "Egypt's national street dish — rice, lentils, macaroni, fried onions, chickpeas, and a vinegar-spiced tomato sauce.",
      400, DL),

    # ════════════════════════ ETHIOPIAN (5 → 9) ════════════════════════
    m('kitfo-ethiopian', 'Kitfo', 'Ethiopian',
      ['Red meat', 'Cream & butter', 'Spice blends', 'Fresh cheese', 'Bread & rolls', 'Peppers & nightshades'],
      "Ethiopian seasoned raw beef tartare with niter kibbeh and mitmita, served with ayib (cottage cheese) and gomen.",
      280, DL),
    m('ye-abesha-gomen', 'Ye\'abesha gomen', 'Ethiopian',
      ['Leafy greens', 'Cream & butter', 'Other vegetables', 'Whole spices', 'Peppers & nightshades'],
      "Ethiopian collard greens slow-cooked with onion, garlic, ginger, and a hit of jalapeño.",
      250, DL),
    m('atakilt-wat', 'Atakilt wat', 'Ethiopian',
      ['Cruciferous vegetables', 'Starchy vegetables', 'Other vegetables', 'Ground spices', 'Whole spices', 'Oils'],
      "Ethiopian cabbage-carrot-potato stew tinted gold with turmeric — fasting-day staple.",
      300, DL),
    m('tibs-special', 'Awaze tibs', 'Ethiopian',
      ['Red meat', 'Peppers & nightshades', 'Spice blends', 'Other vegetables', 'Bread & rolls', 'Oils'],
      "Ethiopian sautéed beef cubes in awaze (berbere-mitmita paste) with onion and jalapeño, served on injera.",
      380, DL),

    # ════════════════════════ SOUTH AFRICAN (5 → 9) ════════════════════
    m('chakalaka-sa', 'Chakalaka', 'South African',
      ['Other vegetables', 'Peppers & nightshades', 'Legumes', 'Spice blends', 'Oils', 'Salt & seasonings'],
      "Spicy South African relish of grated carrot, baked beans, peppers, and curry powder — eaten with pap.",
      200, LSN),
    m('sosaties-sa', 'Sosaties', 'South African',
      ['Red meat', 'Dried fruits', 'Ground spices', 'Other vegetables', 'Oils', 'Spice blends'],
      "Cape Malay marinated lamb skewers with dried apricot, grilled over coals.",
      280, DL),
    m('malva-pudding', 'Malva pudding', 'South African',
      ['Flours', 'Sugar & sweeteners', 'Eggs', 'Cream & butter', 'Jams & preserves', 'Milk'],
      "Cape spongy caramel pudding with an apricot-jam batter, drenched in a butter-cream sauce.",
      150, DESS),
    m('vetkoek-mince', 'Vetkoek with curried mince', 'South African',
      ['Flours', 'Red meat', 'Oils', 'Ground spices', 'Other vegetables', 'Sauces'],
      "South African fried fat-cakes split open and stuffed with curried minced beef.",
      300, DL),

    # ════════════════════════ BRAZILIAN (5 → 10) ═══════════════════════
    m('picanha-brazilian', 'Picanha', 'Brazilian',
      ['Red meat', 'Salt & seasonings', 'Other vegetables', 'Peppers & nightshades', 'Oils'],
      "Brazilian top sirloin cap skewered fat-side-out and grilled over coals — sliced thin, kissed with rock salt.",
      350, DL),
    m('feijao-tropeiro', 'Feijão tropeiro', 'Brazilian',
      ['Legumes', 'Processed meat', 'Eggs', 'Flours', 'Other vegetables', 'Oils'],
      "Brazilian highlands beans tossed with bacon, sausage, and toasted manioc flour.",
      380, DL, contains=['pork']),
    m('feijoada-completa', 'Feijoada (completa)', 'Brazilian',
      ['Legumes', 'Red meat', 'Processed meat', 'Refined grains', 'Other vegetables', 'Citrus', 'Tropical fruits'],
      "Saturday-feast black-bean stew with smoked meats, served with rice, kale, farofa, and orange slices.",
      450, DL, contains=['pork']),
    m('brigadeiros', 'Brigadeiros', 'Brazilian',
      ['Milk', 'Sugar & sweeteners', 'Candy & desserts', 'Cream & butter'],
      "Brazilian condensed-milk chocolate truffles rolled in chocolate sprinkles — birthday-party staple.",
      40, DESS),
    m('pao-de-queijo-brazilian', 'Pão de queijo (cheese bread)', 'Brazilian',
      ['Flours', 'Aged cheese', 'Eggs', 'Oils', 'Milk', 'Salt & seasonings'],
      "Bouncy Brazilian tapioca-flour cheese rolls — naturally gluten-free, served warm.",
      80, LSN),

    # ════════════════════════ CARIBBEAN / JAMAICAN ══════════════════════
    m('curry-goat-jamaican', 'Curry goat', 'Jamaican',
      ['Red meat', 'Starchy vegetables', 'Ground spices', 'Refined grains', 'Peppers & nightshades', 'Fresh herbs'],
      "Jamaican curried goat with potato over rice and peas — Sunday dinner staple.",
      400, DL),
    m('ackee-saltfish-2', 'Ackee and saltfish breakfast', 'Jamaican',
      ['Tropical fruits', 'Canned & cured fish', 'Peppers & nightshades', 'Other vegetables', 'Oils', 'Fresh herbs'],
      "Jamaica's national breakfast — sautéed ackee with salt cod, onion, scotch bonnet, served with festival or fried dumplings.",
      300, BRK),
    m('rice-and-peas-jamaican', 'Rice and peas', 'Jamaican',
      ['Refined grains', 'Legumes', 'Plant milks', 'Whole spices', 'Fresh herbs', 'Salt & seasonings'],
      "Jamaican coconut-and-kidney-bean rice scented with thyme, scallion, and whole Scotch bonnet.",
      300, DL),
    m('escoveitch-fish', 'Escoveitch fish', 'Jamaican',
      ['White fish', 'Pickled vegetables', 'Peppers & nightshades', 'Other vegetables', 'Oils', 'Whole spices'],
      "Jamaican fried fish topped with a vinegary onion-pepper-chayote escabeche.",
      320, DL),
    m('jerk-pork-jamaican', 'Jerk pork', 'Jamaican',
      ['Red meat', 'Spice blends', 'Whole spices', 'Citrus', 'Peppers & nightshades', 'Fresh herbs'],
      "Pimento-wood-smoked pork shoulder rubbed with allspice, scotch bonnet, thyme, and scallion.",
      350, DL, contains=['pork']),

    # ════════════════════════ ARGENTINE (4 → 8) ═════════════════════════
    m('locro-argentino', 'Locro', 'Argentine',
      ['Whole grains', 'Legumes', 'Red meat', 'Processed meat', 'Other vegetables', 'Whole spices'],
      "Argentina's hearty national stew of hominy, beans, beef, and chorizo — served on Independence Day (May 25).",
      450, DL, contains=['pork']),
    m('provoleta-argentine', 'Provoleta', 'Argentine',
      ['Aged cheese', 'Dried herbs', 'Oils', 'Bread & rolls', 'Peppers & nightshades'],
      "Argentine provolone disc grilled until the inside oozes, sprinkled with oregano and chili flakes.",
      150, LSN),
    m('matambre-argentine', 'Matambre arrollado', 'Argentine',
      ['Red meat', 'Other vegetables', 'Eggs', 'Peppers & nightshades', 'Fresh herbs', 'Salt & seasonings'],
      "Argentine flank-steak rolled around hard-boiled eggs, carrots, and bell pepper — sliced cold for picnics.",
      280, LSN),
    m('alfajor-dulce', 'Alfajor', 'Argentine',
      ['Flours', 'Sugar & sweeteners', 'Eggs', 'Milk', 'Cream & butter', 'Candy & desserts'],
      "Argentine cookie sandwich glued with dulce de leche, sometimes coated in coconut or dark chocolate.",
      70, DESS),

    # ════════════════════════ PERUVIAN (5 → 9) ══════════════════════════
    m('ceviche-mixto', 'Ceviche mixto', 'Peruvian',
      ['White fish', 'Shellfish', 'Citrus', 'Peppers & nightshades', 'Other vegetables', 'Fresh herbs', 'Starchy vegetables'],
      "Peruvian seafood ceviche with fish, octopus, and shrimp 'cooked' in lime juice, served with sweet potato and choclo.",
      300, DL),
    m('aji-amarillo-chicken', 'Pollo a la brasa', 'Peruvian',
      ['Poultry', 'Sauces', 'Fresh herbs', 'Ground spices', 'Other vegetables', 'Starchy vegetables'],
      "Peruvian rotisserie chicken marinated in aji amarillo, soy, and cumin — served with ají verde and fries.",
      400, DL),
    m('rocoto-relleno', 'Rocoto relleno', 'Peruvian',
      ['Peppers & nightshades', 'Red meat', 'Eggs', 'Aged cheese', 'Whole spices', 'Starchy vegetables'],
      "Arequipa's bell-pepper-like rocoto stuffed with spiced minced beef, raisins, and olives, baked under cheese.",
      300, DL),
    m('papas-rellenas-peruvian', 'Papas rellenas', 'Peruvian',
      ['Starchy vegetables', 'Red meat', 'Eggs', 'Other vegetables', 'Oils', 'Pickled vegetables'],
      "Mashed-potato shells stuffed with seasoned beef picadillo, breaded and fried golden.",
      220, DL),

    # ════════════════════════ FILIPINO (5 → 9) ══════════════════════════
    m('sisig-filipino', 'Sisig', 'Filipino',
      ['Organ meats', 'Red meat', 'Eggs', 'Peppers & nightshades', 'Citrus', 'Sauces', 'Refined grains'],
      "Pampango sizzling pork-face sisig topped with a raw egg, calamansi, and chili.",
      350, DL, contains=['pork']),
    m('lechon-filipino', 'Lechon', 'Filipino',
      ['Red meat', 'Salt & seasonings', 'Whole spices', 'Fresh herbs', 'Other vegetables', 'Sauces'],
      "Whole-pig spit-roasted Filipino lechon with crackling, basted in citrus and garlic.",
      400, DL, contains=['pork']),
    m('halo-halo', 'Halo-halo', 'Filipino',
      ['Frozen dairy', 'Milk', 'Sugar & sweeteners', 'Legumes', 'Tropical fruits', 'Refined grains'],
      "Filipino shaved-ice dessert layered with sweet beans, jellies, ube ice cream, evaporated milk, and leche flan.",
      400, DESS),
    m('arroz-caldo', 'Arroz caldo', 'Filipino',
      ['Refined grains', 'Poultry', 'Eggs', 'Prepared soups & broths', 'Citrus', 'Whole spices'],
      "Filipino chicken-ginger rice porridge with hard-boiled egg, scallion, and a squeeze of calamansi.",
      400, BRK),

    # ════════════════════════ BURMESE / MYANMAR (0 → 4) ═════════════════
    m('mohinga', 'Mohinga', 'Burmese',
      ['Refined grains', 'White fish', 'Prepared soups & broths', 'Legumes', 'Eggs', 'Fresh herbs', 'Citrus'],
      "Myanmar's national breakfast — catfish-broth noodle soup with split-pea fritters, hard-boiled egg, and lime.",
      400, BRK),
    m('lahpet-thoke', 'Lahpet thoke (tea-leaf salad)', 'Burmese',
      ['Leafy greens', 'Legumes', 'Seeds', 'Peppers & nightshades', 'Citrus', 'Oils'],
      "Burmese fermented tea-leaf salad tossed with fried garlic, peanuts, sesame, lentils, and shredded cabbage.",
      200, LSN),
    m('ohn-no-khao-swe', 'Ohn no khao swè', 'Burmese',
      ['Refined grains', 'Poultry', 'Plant milks', 'Legumes', 'Fresh herbs', 'Citrus', 'Eggs'],
      "Burmese coconut-chicken noodle curry topped with crispy fritters, sliced egg, and chili oil.",
      400, DL),
    m('shan-noodles', 'Shan noodles', 'Burmese',
      ['Refined grains', 'Poultry', 'Pastes & ferments', 'Peppers & nightshades', 'Other vegetables', 'Oils'],
      "Burmese Shan-style chicken or pork noodle salad with pickled mustard greens and ground-peanut sauce.",
      380, DL),

    # ════════════════════════ NEPALI / TIBETAN (0 → 5) ══════════════════
    m('dal-bhat-nepali', 'Dal bhat', 'Nepali',
      ['Refined grains', 'Legumes', 'Other vegetables', 'Ground spices', 'Yogurt', 'Pickled vegetables'],
      "Nepal's two-times-a-day staple — rice, lentil soup, a curried vegetable, achar pickle, and yogurt.",
      450, DL),
    m('momo-nepali', 'Momos', 'Nepali',
      ['Bread & rolls', 'Red meat', 'Other vegetables', 'Sauces', 'Peppers & nightshades', 'Fresh herbs'],
      "Nepali steamed dumplings filled with spiced minced buffalo or chicken, dipped in a tomato-sesame achaar.",
      300, DL),
    m('thukpa-tibetan', 'Thukpa', 'Tibetan',
      ['Refined grains', 'Red meat', 'Other vegetables', 'Prepared soups & broths', 'Ground spices', 'Fresh herbs'],
      "Tibetan hand-pulled noodle soup with yak (or beef), turnip, and spinach — high-altitude warmth.",
      400, DL),
    m('sel-roti', 'Sel roti', 'Nepali',
      ['Refined grains', 'Milk', 'Sugar & sweeteners', 'Cream & butter', 'Ground spices', 'Oils'],
      "Ring-shaped Nepali rice-flour doughnuts fried for Dashain and Tihar festivals.",
      120, BL),
    m('butter-tea-tibetan', 'Po cha (butter tea)', 'Tibetan',
      ['Coffee & tea', 'Cream & butter', 'Milk', 'Salt & seasonings'],
      "Tibetan churned tea with yak butter and salt — sustaining at high altitudes.",
      250, BRK),

    # ════════════════════════ CAMBODIAN / LAO (0 → 5) ═══════════════════
    m('amok-trey', 'Amok trey', 'Cambodian',
      ['White fish', 'Plant milks', 'Pastes & ferments', 'Leafy greens', 'Eggs', 'Whole spices'],
      "Cambodian coconut-fish mousse steamed in banana-leaf cups with kroeung curry paste.",
      300, DL),
    m('lok-lak', 'Lok lak', 'Cambodian',
      ['Red meat', 'Other vegetables', 'Sauces', 'Eggs', 'Citrus', 'Refined grains', 'Salt & seasonings'],
      "Cambodian wok-tossed beef cubes on lettuce-tomato salad, dipped in a peppery lime sauce, with a fried egg over rice.",
      400, DL),
    m('laap-lao', 'Laap (Lao larb)', 'Lao',
      ['Red meat', 'Fresh herbs', 'Whole grains', 'Citrus', 'Peppers & nightshades', 'Sauces'],
      "Lao national dish — minced meat 'salad' with toasted rice powder, lime, fish sauce, and mountains of herbs.",
      250, DL),
    m('tam-mak-hoong', 'Tam mak hoong', 'Lao',
      ['Tropical fruits', 'Peppers & nightshades', 'Sauces', 'Pastes & ferments', 'Citrus', 'Nuts'],
      "Lao green-papaya salad with fermented fish sauce (padaek), crab paste, lime, and chili.",
      200, LSN),
    m('khao-piak-sen', 'Khao piak sen', 'Lao',
      ['Refined grains', 'Poultry', 'Prepared soups & broths', 'Other vegetables', 'Fresh herbs', 'Citrus'],
      "Lao chicken-tapioca noodle soup with pandan-scented broth and fried garlic.",
      400, DL),

    # ════════════════════════ HAWAIIAN (0 → 4) ══════════════════════════
    m('kalua-pig', 'Kalua pig', 'Hawaiian',
      ['Red meat', 'Salt & seasonings', 'Other vegetables', 'Leafy greens'],
      "Imu-roasted pulled pork wrapped in ti leaves and buried with hot stones — luau staple.",
      280, DL, contains=['pork']),
    m('loco-moco', 'Loco moco', 'Hawaiian',
      ['Refined grains', 'Red meat', 'Eggs', 'Sauces', 'Other vegetables'],
      "Hawaiian comfort plate of rice topped with a hamburger patty, fried egg, and brown gravy.",
      400, DL),
    m('hawaiian-poke-bowl', 'Hawaiian poke bowl', 'Hawaiian',
      ['Oily fish', 'Refined grains', 'Other vegetables', 'Seeds', 'Sauces', 'Fresh herbs'],
      "Diced raw ahi tuna marinated in shoyu, sesame, and limu, served over rice with edamame and avocado.",
      380, DL),
    m('lau-lau', 'Lau lau', 'Hawaiian',
      ['Red meat', 'Leafy greens', 'White fish', 'Salt & seasonings'],
      "Pork and butterfish wrapped in luau (taro) leaves and ti leaves, then steamed for hours.",
      300, DL, contains=['pork']),

    # ════════════════════════ NATIVE-AMERICAN (0 → 3) ═══════════════════
    m('frybread', 'Indian fry bread', 'Native American',
      ['Flours', 'Oils', 'Salt & seasonings', 'Sugar & sweeteners'],
      "Diaspora-era Navajo fry bread — yeastless dough fried until golden, the canvas for Indian tacos or honey-and-cinnamon.",
      150, LSN),
    m('three-sisters-stew', 'Three-sisters stew', 'Native American',
      ['Legumes', 'Starchy vegetables', 'Other vegetables', 'Whole grains', 'Salt & seasonings', 'Fresh herbs'],
      "Squash, corn, and beans simmered together — the agricultural trinity of pre-contact North America.",
      350, DL),
    m('bison-stew-native', 'Bison-and-wild-rice stew', 'Native American',
      ['Red meat', 'Whole grains', 'Other vegetables', 'Mushrooms', 'Whole spices', 'Prepared soups & broths'],
      "Plains-style bison and wild rice stew with foraged mushrooms and turnips.",
      400, DL),

    # ════════════════════════ FRENCH (14 → 18) ══════════════════════════
    m('boeuf-bourguignon-2', 'Bœuf bourguignon (Burgundy-style)', 'French',
      ['Red meat', 'Alcoholic beverages', 'Processed meat', 'Other vegetables', 'Mushrooms', 'Fresh herbs'],
      "Burgundy beef braise in red wine with lardons, pearl onions, and mushrooms.",
      400, DL, contains=['pork', 'alcohol']),
    m('confit-de-canard', 'Confit de canard', 'French',
      ['Poultry', 'Starchy vegetables', 'Salt & seasonings', 'Whole spices', 'Oils', 'Other vegetables'],
      "Gascon duck legs cured in salt then slow-cooked in their own fat, served with pommes sarladaises.",
      350, DL),
    m('soupe-a-l-oignon', 'Soupe à l\'oignon gratinée', 'French',
      ['Other vegetables', 'Prepared soups & broths', 'Bread & rolls', 'Aged cheese', 'Alcoholic beverages', 'Cream & butter'],
      "Caramelized-onion soup capped with crouton and a blistered Gruyère crust.",
      350, DL, contains=['alcohol']),
    m('blanquette-de-veau', 'Blanquette de veau', 'French',
      ['Red meat', 'Other vegetables', 'Mushrooms', 'Cream & butter', 'Eggs', 'Refined grains', 'Citrus'],
      "French white veal stew thickened with egg yolk and cream — bistro classique.",
      400, DL),

    # ════════════════════════ ITALIAN-AMERICAN (1 → 4) ══════════════════
    m('chicken-parm-2', 'Chicken parmigiana', 'Italian-American',
      ['Poultry', 'Bread & rolls', 'Eggs', 'Aged cheese', 'Fresh cheese', 'Sauces', 'Refined grains'],
      "Breaded chicken cutlet smothered in red sauce and mozzarella, baked and served over spaghetti.",
      450, DL),
    m('chicken-piccata', 'Chicken piccata', 'Italian-American',
      ['Poultry', 'Citrus', 'Cream & butter', 'Pickled vegetables', 'Alcoholic beverages', 'Flours', 'Fresh herbs'],
      "Pounded chicken cutlets in a lemon-caper-white-wine butter sauce.",
      320, DL, contains=['alcohol']),
    m('baked-ziti', 'Baked ziti', 'Italian-American',
      ['Refined grains', 'Fresh cheese', 'Aged cheese', 'Red meat', 'Sauces', 'Fresh herbs', 'Cream & butter'],
      "American-Italian baked pasta with ricotta layers and a sausage-tomato sauce.",
      400, DL),

    # ════════════════════════ ASIAN (generic, 1 → 3) ════════════════════
    m('hot-pot-asian-generic', 'Asian hot pot', 'Asian',
      ['Red meat', 'Shellfish', 'Soy products', 'Other vegetables', 'Mushrooms', 'Refined grains'],
      "Build-your-own boiling pot with thinly-sliced meats, tofu, fish balls, leafy greens, and noodles — eaten communally.",
      450, DL),
    m('chinese-american-buffet', 'Asian buffet plate', 'Asian',
      ['Refined grains', 'Poultry', 'Other vegetables', 'Sauces', 'Eggs', 'Shellfish'],
      "Mixed-Asian buffet — sweet-and-sour something, fried rice, lo mein, and a couple of mall-court favorites.",
      450, DL),

    # ════════════════════════ MEDITERRANEAN (generic) ═══════════════════
    m('mediterranean-bowl', 'Mediterranean grain bowl', 'Mediterranean',
      ['Whole grains', 'Poultry', 'Other vegetables', 'Fresh cheese', 'Legumes', 'Oils', 'Pickled vegetables', 'Fresh herbs'],
      "Quinoa, grilled chicken, hummus, cucumber, tomato, feta, kalamatas, and tzatziki.",
      450, DL),
    m('crudo-and-flatbread', 'Crudo & flatbread plate', 'Mediterranean',
      ['Oily fish', 'Citrus', 'Oils', 'Fresh herbs', 'Bread & rolls', 'Salt & seasonings'],
      "Plate of citrus-dressed raw fish (crudo) with a hot flatbread and good olive oil.",
      280, DL),

    # ════════════════════════ AMERICAN-SOUTHERN (2 → 6) ═════════════════
    m('biscuits-fried-chicken', 'Buttermilk biscuits & fried chicken', 'American-Southern',
      ['Poultry', 'Flours', 'Cream & butter', 'Eggs', 'Milk', 'Spice blends', 'Oils'],
      "Crispy fried chicken on top of split buttermilk biscuits with hot honey.",
      400, BL),
    m('crawfish-boil', 'Crawfish boil', 'American-Southern',
      ['Shellfish', 'Starchy vegetables', 'Other vegetables', 'Processed meat', 'Whole spices', 'Salt & seasonings'],
      "Louisiana mudbug boil — crawfish, sausage, corn, and potato dumped on a newspapered table.",
      450, DL, contains=['pork']),
    m('jambalaya', 'Jambalaya', 'American-Southern',
      ['Refined grains', 'Processed meat', 'Poultry', 'Shellfish', 'Peppers & nightshades', 'Other vegetables', 'Spice blends'],
      "Creole one-pot rice with andouille, chicken, and shrimp in a holy-trinity sofrito.",
      450, DL, contains=['pork']),
    m('gumbo-southern', 'Gumbo', 'American-Southern',
      ['Shellfish', 'Processed meat', 'Refined grains', 'Other vegetables', 'Peppers & nightshades', 'Spice blends', 'Oils'],
      "Cajun shrimp-and-okra gumbo over rice, thickened with dark roux and a kiss of filé.",
      450, DL, contains=['pork']),
]


def main():
    with PATH.open(encoding='utf-8') as f:
        meals = json.load(f)
    by_id = {x['id']: x for x in meals}
    added = 0; collided = 0
    for new in NEW:
        if new['id'] in by_id:
            collided += 1; continue
        meals.append(new); added += 1
    with PATH.open('w', encoding='utf-8') as f:
        json.dump(meals, f, ensure_ascii=False, indent=2); f.write('\n')
    print(f'meals.json now contains {len(meals)} curated meals.')
    print(f'  added:    {added}')
    print(f'  collided: {collided}')


if __name__ == '__main__':
    main()
