"""Map from recipe_taxonomy.csv subcategory strings to the project's current
ingredient_categories. Built by surveying every subcategory token that
appears in the corpus and assigning it by culinary knowledge.

The point of using subcategories rather than the CSV's coarse `categories`
column is fidelity. "Fruits" alone can't tell apple from banana, so the
existing Phase 36 remap silently turns banana bread into "Temperate fruits"
even though banana is tropical. Subcategories preserve "Apple" vs "Banana"
vs "Citrus" vs "Stone fruit", so the rebuilt categorization actually tracks
what the recipe contains.

When a subcategory maps to nothing meaningful in the current taxonomy
(e.g., "Other", "Stabilizers"), we map it to None and ignore it.
"""

SUB_TO_CATEGORY: dict[str, str | None] = {
    # ---------------- Vegetables ----------------
    "Allium": "Other vegetables",
    "Alliums": "Other vegetables",
    "Aromatics": "Other vegetables",
    "Bulbs": "Other vegetables",
    "Pods": "Other vegetables",
    "Stalks": "Other vegetables",
    "Shoots": "Other vegetables",
    "Sprouts": "Other vegetables",
    "Celery": "Other vegetables",
    "Carrot": "Starchy vegetables",
    "Cucumber": "Other vegetables",
    "Asparagus": "Other vegetables",
    "Summer squash": "Other vegetables",
    "Squash": "Starchy vegetables",   # ambiguous - default to winter form
    "Winter squash": "Starchy vegetables",
    "Eggplant": "Peppers & nightshades",
    "Avocado": "Other vegetables",
    "Tomato": "Peppers & nightshades",
    "Tomatoes": "Peppers & nightshades",
    "Tomato products": "Peppers & nightshades",
    "Tomato condiments": "Sauces",
    "Peppers": "Peppers & nightshades",
    "Bell pepper": "Peppers & nightshades",
    "Pimentos": "Peppers & nightshades",
    "Chili peppers": "Peppers & nightshades",
    "Olives": "Pickled vegetables",
    "Green beans": "Other vegetables",
    "Cabbage": "Leafy greens",
    "Lettuce": "Leafy greens",
    "Salad greens": "Leafy greens",
    "Cooking greens": "Leafy greens",
    "Spinach": "Leafy greens",
    "Kale": "Leafy greens",
    "Chard": "Leafy greens",
    "Bitter greens": "Leafy greens",
    "Collards": "Leafy greens",
    "Arugula": "Leafy greens",
    "Asian greens": "Leafy greens",
    "Wild greens": "Leafy greens",
    "Sea vegetables": "Other vegetables",
    "Mushroom": "Mushrooms",
    "Mushrooms": "Mushrooms",
    "Broccoli": "Cruciferous vegetables",
    "Cauliflower": "Cruciferous vegetables",
    "Brussels sprouts": "Cruciferous vegetables",
    "Brassicas": "Cruciferous vegetables",
    "Root brassicas": "Cruciferous vegetables",
    "Flower vegetables": "Cruciferous vegetables",
    "Root vegetables": "Starchy vegetables",
    "Potatoes": "Starchy vegetables",
    "Potato": "Starchy vegetables",
    "Sweet potato": "Starchy vegetables",
    "Beet": "Starchy vegetables",
    "Corn": "Starchy vegetables",
    "Tropical starches": "Starchy vegetables",
    "Cassava products": "Starchy vegetables",
    "Tubers": "Starchy vegetables",
    "Gourds": "Starchy vegetables",
    "Pickled": "Pickled vegetables",
    "Pickled cucumber & cabbage": "Pickled vegetables",
    "Pickled vegetables": "Pickled vegetables",
    "Fermented vegetables": "Pickled vegetables",
    "Other pickled": "Pickled vegetables",
    "Capers": "Pickled vegetables",

    # ---------------- Fruits ----------------
    "Citrus": "Citrus",
    "Apple": "Temperate fruits",
    "Pear": "Temperate fruits",
    "Grape": "Temperate fruits",
    "Stone fruit": "Temperate fruits",
    "Stone fruits": "Temperate fruits",
    "Melon": "Temperate fruits",
    "Melons": "Temperate fruits",
    "Other fruits": "Temperate fruits",
    "Florals": "Temperate fruits",
    "Strawberry": "Berries",
    "Blueberry": "Berries",
    "Raspberry": "Berries",
    "Blackberry": "Berries",
    "Cranberry": "Berries",
    "Berries": "Berries",
    "Tropical": "Tropical fruits",
    "Banana": "Tropical fruits",
    "Coconut": "Tropical fruits",
    "Raisin": "Dried fruits",
    "Date": "Dried fruits",
    "Prune": "Dried fruits",
    "Dried apricot": "Dried fruits",
    "Dried cranberry": "Dried fruits",
    "Dried fruits": "Dried fruits",
    "Dried": "Dried fruits",

    # ---------------- Grains ----------------
    "Wheat": "Whole grains",
    "Whole grains": "Whole grains",
    "Oats": "Whole grains",
    "Barley": "Whole grains",
    "Pseudocereal": "Whole grains",
    "Pseudocereals": "Whole grains",
    "Wheat flours": "Flours",
    "Other flours": "Flours",
    "Nut flours": "Flours",
    "Legume flours": "Flours",
    "Wheat protein": "Flours",
    "Rice": "Refined grains",
    "Pasta": "Refined grains",
    "Noodles": "Refined grains",
    "Starches": "Refined grains",
    "Cereals": "Refined grains",
    "Bread": "Bread & rolls",
    "Rolls": "Bread & rolls",
    "Tortilla": "Bread & rolls",
    "Tortillas": "Bread & rolls",
    "Cornbread": "Bread & rolls",
    "Flatbread": "Bread & rolls",
    "Pizza dough": "Bread & rolls",
    "Wrappers": "Bread & rolls",
    "Bread crumbs": "Bread & rolls",
    "Croutons": "Bread & rolls",
    "Stuffing mixes": "Bread & rolls",
    "Muffins": "Baked snacks & pastries",
    "Biscuits": "Baked snacks & pastries",
    "Pretzels": "Baked snacks & pastries",
    "Crackers": "Baked snacks & pastries",
    "Graham crackers": "Baked snacks & pastries",
    "Pastries": "Baked snacks & pastries",
    "Pastry": "Baked snacks & pastries",
    "Cookies": "Baked snacks & pastries",
    "Cake mixes": "Prepared mixes",
    "Baking mixes": "Prepared mixes",
    "Cookie mixes": "Prepared mixes",

    # ---------------- Protein (animal) ----------------
    "Chicken": "Poultry",
    "Turkey": "Poultry",
    "Duck": "Poultry",
    "Goose": "Poultry",
    "Ground poultry": "Poultry",
    "Game bird": "Poultry",
    "Beef": "Red meat",
    "Ground beef": "Red meat",
    "Pork": "Red meat",
    "Lamb": "Red meat",
    "Veal": "Red meat",
    "Game": "Red meat",
    "Cured pork": "Processed meat",
    "Cured sausage": "Processed meat",
    "Cured meat": "Processed meat",
    "Sausage": "Processed meat",
    "Fresh sausage": "Processed meat",
    "Smoked sausage": "Processed meat",
    "Deli": "Processed meat",
    "Canned meat": "Processed meat",
    "Whole egg": "Eggs",
    "Egg yolk": "Eggs",
    "Egg white": "Eggs",
    "Eggs": "Eggs",
    "Cod": "White fish",
    "Tilapia": "White fish",
    "Haddock": "White fish",
    "Pollock": "White fish",
    "Flatfish": "White fish",
    "Saltwater white fish": "White fish",
    "Salmon": "Oily fish",
    "Tuna": "Oily fish",
    "Mackerel": "Oily fish",
    "Sardines": "Oily fish",
    "Anchovies": "Oily fish",
    "Trout": "Oily fish",
    "Halibut": "Oily fish",
    "Oily fish": "Oily fish",
    "Roe": "Canned & cured fish",
    "Freshwater fish": "Freshwater fish",
    "Shrimp": "Shellfish",
    "Crab": "Shellfish",
    "Lobster": "Shellfish",
    "Scallops": "Shellfish",
    "Mussels": "Shellfish",
    "Oysters": "Shellfish",
    "Bivalves": "Shellfish",
    "Crustaceans": "Shellfish",
    "Cephalopods": "Shellfish",
    "Mollusks": "Shellfish",
    "Aquatic": "Shellfish",
    "Cured fish": "Canned & cured fish",
    "Liver": "Organ meats",
    "Kidney": "Organ meats",
    "Heart": "Organ meats",
    "Tripe": "Organ meats",
    "Tongue": "Organ meats",
    "Sweetbreads": "Organ meats",
    "Other animal products": None,

    # ---------------- Protein (plant) ----------------
    "Beans": "Legumes",
    "Lentil": "Legumes",
    "Lentils": "Legumes",
    "Chickpea": "Legumes",
    "Peas": "Legumes",
    "Soy": "Soy products",
    "Plant protein": "Meat alternatives",

    # ---------------- Dairy ----------------
    "Cow milk": "Milk",
    "Cultured milk": "Milk",
    "Concentrated milk": "Milk",
    "Dairy beverages": "Milk",
    "Animal milk": "Milk",
    "Fermented milk": "Milk",
    "Plant milks": "Plant milks",
    "Regular yogurt": "Yogurt",
    "Greek yogurt": "Yogurt",
    "Strained yogurt": "Yogurt",
    "Yogurt-style": "Yogurt",
    "Yogurt drink": "Yogurt",
    "Cultured cream": "Fermented dairy",
    "Cream cheese": "Fresh cheese",
    "Cottage": "Fresh cheese",
    "Ricotta": "Fresh cheese",
    "Feta": "Fresh cheese",
    "Mozzarella": "Fresh cheese",
    "Fresh cheese": "Fresh cheese",
    "Stretched curd": "Fresh cheese",
    "Cheddar": "Aged cheese",
    "Parmesan": "Aged cheese",
    "Aged cheese": "Aged cheese",
    "Swiss": "Aged cheese",
    "Blue": "Aged cheese",
    "Blue cheese": "Aged cheese",
    "Semi-soft cheese": "Aged cheese",
    "Hard grating cheese": "Aged cheese",
    "Soft-ripened": "Aged cheese",
    "Shredded cheese": "Aged cheese",
    "Processed cheese": "Processed cheese",
    "Cream": "Cream & butter",
    "Butter": "Cream & butter",
    "Clarified butter": "Cream & butter",
    "Spiced butters": "Cream & butter",
    "Butter alternatives": "Margarine & shortening",
    "Whipped toppings": "Cream & butter",
    "Dairy sauces": "Sauces",
    "Ice cream": "Frozen dairy",
    "Frozen desserts": "Frozen dairy",

    # ---------------- Nuts & seeds ----------------
    "Almond": "Nuts",
    "Pecan": "Nuts",
    "Walnut": "Nuts",
    "Cashew": "Nuts",
    "Hazelnut": "Nuts",
    "Peanut": "Nuts",
    "Pistachio": "Nuts",
    "Tree nuts": "Nuts",
    "Nut butters": "Nut butters",
    "Peanut butter": "Nut butters",
    "Almond butter": "Nut butters",
    "Sesame paste": "Nut butters",
    "Seed butters": "Nut butters",
    "Seeds": "Seeds",
    "Sunflower seed": "Seeds",
    "Pumpkin seed": "Seeds",
    "Sesame": "Seeds",
    "Flax": "Seeds",
    "Chia": "Seeds",

    # ---------------- Fats & oils ----------------
    "Olive oil": "Oils",
    "Vegetable oils": "Oils",
    "Canola oil": "Oils",
    "Sesame oil": "Oils",
    "Coconut oil": "Oils",
    "Avocado oil": "Oils",
    "Infused oils": "Oils",
    "Animal fats": "Oils",
    "Solid fats": "Margarine & shortening",
    "Margarine": "Margarine & shortening",
    "Shortening": "Margarine & shortening",

    # ---------------- Sweets ----------------
    "Sugar": "Sugar & sweeteners",
    "Sweeteners": "Sugar & sweeteners",
    "Sugar substitutes": "Sugar & sweeteners",
    "Honey": "Sugar & sweeteners",
    "Syrup": "Sugar & sweeteners",
    "Syrups": "Sugar & sweeteners",
    "Chocolate": "Candy & desserts",
    "Cocoa": "Candy & desserts",
    "Confectionery": "Candy & desserts",
    "Puddings": "Candy & desserts",
    "Pie fillings": "Candy & desserts",
    "Gelatins": "Candy & desserts",
    "Fruit preserves": "Jams & preserves",
    "Preserves": "Jams & preserves",
    "Sweet spreads": "Jams & preserves",
    "Chutneys": "Jams & preserves",

    # ---------------- Herbs & spices ----------------
    "Soft herbs": "Fresh herbs",
    "Hard herbs": "Fresh herbs",
    "Herb sauces": "Sauces",          # pesto-style
    "Dried herbs": "Dried herbs",
    "Ground spices": "Ground spices",
    "Chili powders": "Ground spices",
    "Seed spices": "Ground spices",
    "Whole spices": "Whole spices",
    "American blends": "Spice blends",
    "Indian blends": "Spice blends",
    "Mexican blends": "Spice blends",
    "European blends": "Spice blends",
    "Chinese blends": "Spice blends",
    "Japanese blends": "Spice blends",
    "Caribbean blends": "Spice blends",
    "Latin blends": "Spice blends",
    "Middle Eastern blends": "Spice blends",
    "Ethiopian blends": "Spice blends",
    "Levantine blends": "Spice blends",
    "Egyptian blends": "Spice blends",
    "North African blends": "Spice blends",
    "Seasoning mixes": "Spice blends",
    "Salt": "Salt & seasonings",
    "Seasoned salts": "Salt & seasonings",
    "Extracts": "Extracts & essences",
    "Emulsions": "Extracts & essences",
    "Floral waters": "Extracts & essences",

    # ---------------- Condiments & sauces ----------------
    "Mixed condiments": "Sauces",
    "Hot sauces": "Sauces",
    "Mustards": "Sauces",
    "Asian sauces": "Sauces",
    "Vinegars": "Dressings & dips",
    "Salad dressings": "Dressings & dips",
    "Spreads": "Dressings & dips",
    "Chili pastes": "Pastes & ferments",
    "Curry pastes": "Pastes & ferments",
    "Fermented pastes": "Pastes & ferments",
    "Mexican pastes": "Pastes & ferments",
    "Latin American pastes": "Pastes & ferments",
    "Indian curry pastes": "Pastes & ferments",
    "Broths & stocks": "Prepared soups & broths",

    # ---------------- Beverages ----------------
    "Coffee": "Coffee & tea",
    "Tea": "Coffee & tea",
    "Soft drinks": "Soft drinks",
    "Cocktail mixers": "Soft drinks",
    "Fruit juices": "Juices",
    "Fruit nectars": "Juices",
    "Wine": "Alcoholic beverages",
    "Beer": "Alcoholic beverages",
    "Rum": "Alcoholic beverages",
    "Vodka": "Alcoholic beverages",
    "Brandy": "Alcoholic beverages",
    "Whisky": "Alcoholic beverages",
    "Tequila": "Alcoholic beverages",
    "Gin": "Alcoholic beverages",
    "Liqueurs": "Alcoholic beverages",
    "Cider": "Alcoholic beverages",   # in this corpus mostly hard cider context

    # ---------------- Baking ----------------
    "Leaveners": "Baking ingredients",
    "Stabilizers": "Baking ingredients",
    "Setting agents": "Baking ingredients",
    "Food coloring": "Baking ingredients",

    # ---------------- Pantry category buckets (regional shelves) ----------------
    # These are "pantry sections" that bundle several specialty items. We
    # assign them to Sauces as the most common interpretation (soy sauce,
    # fish sauce, gochujang, etc.).
    "Japanese pantry": "Sauces",
    "Chinese pantry": "Sauces",
    "Korean pantry": "Sauces",
    "Vietnamese pantry": "Sauces",
    "Southeast Asian pantry": "Sauces",

    # ---------------- Unclassified ----------------
    "Other": None,
}
