"""
Rewrite the `notes` field in src/data/meals.json with chef-style
descriptions — concise, visualizable, focused on cooking method and
presentation rather than ingredient listing.

Usage: python scripts/rewrite_meal_notes.py
"""

import json
import os
import sys

# Each entry: meal_id -> new notes (chef-style, ~25-50 words).
# Goal: a stranger to the dish can picture it from the description.
NOTES = {
    "chicken-rice-bowl": "Sliced grilled chicken fanned over a bed of fluffy white rice, finished with charred vegetables and a drizzle of pan jus — a clean weeknight bowl that satisfies without weighing you down.",
    "chicken-stir-fry": "Strips of chicken seared in a screaming-hot wok with bell peppers, broccoli, and onion, glossed in a savory soy-garlic sauce and tipped over steamed rice.",
    "salmon-plate": "A blushing fillet of salmon, skin crackling-crisp, plated beside roasted potatoes and a tangle of bright greens — restaurant comfort, weeknight-easy.",
    "sashimi-platter": "Glassy slices of raw tuna, salmon, and yellowtail fanned across a chilled board with pickled ginger, a green daub of wasabi, and a side of soy.",
    "tuna-salad": "Flaked tuna folded into a lemon-bright dressing with celery and red onion, mounded over crisp greens — a brown-bag classic done well.",
    "fish-and-chips": "Golden-battered white fish that shatters at first bite, paired with thick salt-flecked chips, a scoop of mushy peas, and a wedge of lemon.",
    "shrimp-pasta": "Pink shrimp tossed in butter, garlic, and white wine, draped over al dente pasta with a snow of parmesan and fresh parsley.",
    "burger": "A char-edged beef patty stacked with lettuce, tomato, onion, and pickles between a soft toasted bun — the original handheld comfort.",
    "cheeseburger": "A juicy beef patty crowned with a melting slice of American cheese, layered with crisp lettuce, tomato, and pickles in a buttery toasted bun.",
    "steak-dinner": "A rested ribeye sliced against the grain, plated with buttery mashed potatoes and a stem of charred green vegetable — the steakhouse blueprint.",
    "bacon-and-eggs": "Eggs cooked sunny-side up, yolks ready to break across the plate, served with crisp bacon and buttered toast.",
    "omelet-veg-cheese": "A pale-gold three-egg omelet folded around a melting heap of sautéed peppers, mushrooms, and shredded cheese.",
    "yogurt-parfait": "Tangy Greek yogurt layered with fresh berries, a drizzle of honey, and toasted granola for crunch — served in a tall glass.",
    "berry-smoothie": "Frozen berries blended with yogurt and a splash of milk into a thick purple pour, optionally sweetened with honey.",
    "cereal-bowl": "A cold bowl of crisp flakes and milk with sliced banana on top — the unglamorous classic that just works.",
    "oatmeal-berries": "Creamy steel-cut oats topped with juicy berries, a scatter of nuts, and a swirl of milk and brown sugar.",
    "cheese-plate": "An assortment of sliced and cubed cheeses on a wooden board with dried fruit, honey, and a fan of crackers.",
    "greek-salad": "Crisp cucumber, ripe tomato, red onion, and briny olives tossed in olive oil and oregano, crowned with a thick slab of feta.",
    "caesar-salad": "Crunchy romaine tossed in a garlicky anchovy-laced dressing, finished with parmesan shards and golden croutons.",
    "hummus-plate": "A pool of silky, lemon-bright hummus dimpled with olive oil, served with warm pita triangles and a scatter of crudités.",
    "bean-burrito": "Refried beans, melted cheese, and a spoon of salsa wrapped tight in a soft warm flour tortilla, griddled until lightly toasted.",
    "vegan-bowl": "A composed bowl of warm grains, roasted vegetables, beans, and a tahini drizzle — plant-only and deeply satisfying.",
    "tofu-stir-fry": "Cubes of golden-seared tofu tossed with crisp vegetables in a glossy ginger-soy sauce, served over steamed rice.",
    "pb-sandwich": "Creamy peanut butter and a thin slick of jam between two slices of soft bread — the lunchbox staple.",
    "pasta-red-sauce": "Al dente pasta tossed in a long-simmered tomato sauce, finished with torn basil and a generous shower of parmesan.",
    "fruit-and-nuts": "A small handful of fresh sliced fruit beside a scatter of roasted, salted nuts — a snack that feels grown-up.",
    "pancakes-syrup": "A stack of buttermilk pancakes, edges lacy and golden, crowned with a melting pat of butter and a slow pour of maple syrup.",
    "mac-and-cheese": "Tender macaroni in a silky cheddar-cream sauce, baked under a crackling breadcrumb crust — the ultimate comfort.",
    "cobb-salad": "Composed rows of grilled chicken, crisp bacon, avocado, hard-boiled egg, and blue cheese over chopped romaine — a salad that eats like a meal.",
    "bbq-plate": "Smoky pulled pork or sliced brisket lacquered with sauce, served with creamy coleslaw, cornbread, and a soft bun.",
    "thanksgiving-plate": "A slice of roast turkey blanketed in gravy, beside mashed potatoes, sage stuffing, candied yams, green beans, and a spoon of cranberry sauce.",
    "biscuits-and-gravy": "Flaky buttermilk biscuits split open and smothered in peppery sausage gravy — a Southern Sunday plate.",
    "chicken-and-waffles": "Crisp buttermilk-fried chicken perched on golden waffles, syrup pooling at the edges and a knob of butter melting on top.",
    "club-sandwich": "A triple-decker tower of toasted bread layered with turkey, bacon, lettuce, tomato, and mayo, skewered into four neat triangles.",
    "reuben-sandwich": "Corned beef, Swiss cheese, sauerkraut, and Russian dressing griddled between slices of rye until the cheese is melting and the bread is buttery-crisp.",
    "buffalo-wings": "Crackling fried chicken wings tumbled in a glossy butter-hot-sauce, served with celery sticks and a cup of cool blue cheese dressing.",
    "chili-con-carne": "A slow-simmered bowl of ground beef, beans, tomato, and chiles — thick, smoky, and topped with cheese, sour cream, and scallions.",
    "philly-cheesesteak": "Thin shaved beef and sweated onions piled into a soft hoagie roll, draped with melted provolone or Cheez Whiz.",
    "meatloaf-mashed-potato": "A thick slab of glazed meatloaf beside a soft mound of mashed potatoes pooling with gravy — diner comfort.",
    "lobster-roll": "Cool lobster meat barely bound with mayo (or warmed in butter), tucked into a buttery, griddled split-top bun.",
    "full-english-breakfast": "Eggs, bacon, sausages, baked beans, grilled tomato, mushrooms, and a slice of toast — the full plate, all at once.",
    "shepherds-pie": "Spiced minced lamb and peas beneath a crown of mashed potato, baked until the top peaks are crisp and golden.",
    "bangers-and-mash": "Plump pork sausages over creamy mashed potatoes, smothered with rich onion gravy — pub comfort.",
    "ploughmans-lunch": "A casual lunch board of cheese, cold ham, pickles, crusty bread, butter, and a tart apple.",
    "sunday-roast": "Sliced roast beef with crisp Yorkshire pudding, roast potatoes, root vegetables, and a glossy ladle of gravy.",
    "scones-cream-jam": "Warm crumbly scones split and piled high with thick clotted cream and strawberry jam, alongside a pot of tea.",
    "beef-wellington": "A rosy beef tenderloin wrapped in mushroom duxelles and golden puff pastry, sliced to reveal blush-pink centers.",
    "toad-in-the-hole": "Plump pork sausages baked into a billowing golden Yorkshire pudding, served with onion gravy.",
    "croque-monsieur": "Ham and Gruyère sandwiched in buttered bread, the top blanketed in béchamel and broiled until bubbling and bronzed.",
    "ratatouille": "Slow-stewed eggplant, zucchini, peppers, onion, and tomato in olive oil and herbs — silky, savory, deeply Provençal.",
    "beef-bourguignon": "Chunks of beef braised slowly in red wine with mushrooms, pearl onions, and bacon until forktender and gravy-rich.",
    "nicoise-salad": "Composed wedges of seared tuna, green beans, olives, hard-boiled egg, and small potatoes over greens with a sharp vinaigrette.",
    "omelette-french": "A pale, just-set omelette rolled into a slim cylinder, the inside still loose — buttery, custardy, deceptively simple.",
    "coq-au-vin": "Chicken simmered low and slow in red wine with mushrooms, lardons, and pearl onions until the sauce turns silky.",
    "bouillabaisse": "A saffron-stained Provençal seafood stew of fish and shellfish, served with crusty bread and a smear of garlicky rouille.",
    "quiche-lorraine": "A blind-baked tart shell holding a custard of cream and eggs, studded with smoky lardons — set just enough to slice clean.",
    "cassoulet": "A bubbling earthenware crock of white beans slow-cooked with duck confit, sausage, and pork, capped with a crisp golden crust.",
    "crepes-savory": "Paper-thin buckwheat crêpes folded around ham, Gruyère, and a runny egg, edges crisp and lacy.",
    "caprese": "Alternating slices of milky mozzarella and ripe tomato, finished with torn basil, flaky salt, and a slick of olive oil.",
    "pasta-carbonara": "Hot spaghetti tossed with crisp guanciale, sharp pecorino, and egg yolks into a glossy, peppery sauce — no cream, just emulsion.",
    "pasta-bolognese": "Tagliatelle coiled in a long-simmered meat ragù — rich, savory, finished with parmesan and a drag of butter.",
    "pesto-pasta": "Trofie or trenette dressed with a vivid green basil-pine-nut-parmesan pesto, tossed with cubed potato and green beans Ligurian-style.",
    "pasta-amatriciana": "Bucatini in a spicy tomato sauce rich with crisp guanciale and pecorino — Roman, fiery, and unapologetic.",
    "risotto-mushroom": "Creamy short-grain rice stirred patiently with wine and stock until al dente, folded with seared wild mushrooms and parmesan.",
    "risotto-milanese": "Saffron-stained risotto, golden and glossy, finished with butter, parmesan, and a hint of beef marrow.",
    "pizza-margherita": "A blistered-edge Neapolitan crust topped with crushed tomato, torn fior di latte, basil leaves, and a slick of olive oil.",
    "osso-buco": "Cross-cut veal shanks braised until the meat falls off the bone, the marrow scooped onto crusty bread and finished with gremolata.",
    "lasagna": "Layers of pasta sheets, slow-cooked meat ragù, béchamel, and parmesan, baked until the top is bubbling and burnished.",
    "paella": "Saffron-tinted short-grain rice cooked wide in a shallow pan with chicken, chorizo, shellfish, and peas — the crust on the bottom (socarrat) is the prize.",
    "tortilla-espanola": "A thick wedge of egg-and-potato omelette set with sweet onion, served warm or room-temperature, sturdy enough to slice and pass around.",
    "gazpacho": "A chilled raw-tomato soup blended with cucumber, pepper, garlic, and olive oil — bright, savory, and meant for hot afternoons.",
    "patatas-bravas": "Crisp-edged fried potato cubes drizzled with a smoky brava sauce and a swirl of garlic aioli — a tapas mainstay.",
    "bacalhau-com-natas": "Flakes of salt cod layered with onions and thin potato slices in cream, baked until the top is bubbling and golden.",
    "schnitzel": "A pounded-thin veal cutlet breaded and pan-fried to a crackling golden coat, served with lemon wedges and a side of potato salad.",
    "rosti": "Coarsely grated potato pressed into a crisp golden pancake, served alongside eggs, sausage, or smoked salmon.",
    "sauerbraten": "Marinated pot-roast beef slowly braised, then served sliced with a tangy gingerbread-thickened gravy and red cabbage.",
    "raclette-platter": "Half-wheel cheese melted by the fire, scraped onto small potatoes, cornichons, and slices of cured ham.",
    "muesli-bowl": "Rolled oats soaked in milk or yogurt with grated apple, dried fruit, and toasted nuts — Swiss bircher-style.",
    "spaetzle-cheese": "Soft, irregular egg-noodle dumplings layered with melted Emmental and crisped onions — Germany's answer to mac and cheese.",
    "currywurst": "Sliced grilled bratwurst doused in a tangy curry-spiced tomato sauce, dusted with curry powder, served with fries or a roll.",
    "pierogi-potato-cheese": "Half-moon dumplings stuffed with potato and farmer's cheese, boiled then pan-fried until edges crisp, served with sour cream and onions.",
    "borscht": "A magenta beet soup, faintly sour and sweet, served hot with a dollop of sour cream and a sprig of dill.",
    "goulash": "A paprika-stained Hungarian stew of beef and onions simmered slowly until the meat surrenders, served with bread or buttered noodles.",
    "blini-caviar": "Small warm yeasted pancakes topped with a dab of crème fraîche and a glistening spoon of caviar.",
    "stuffed-cabbage": "Tender cabbage leaves rolled around a savory pork-and-rice filling, simmered in a sweet-sour tomato sauce.",
    "smorgasbord-plate": "A composed plate of pickled herring, cured salmon, hard cheese, rye crackers, boiled eggs, and dill new potatoes.",
    "gravlax-plate": "Translucent slices of dill-and-sugar-cured salmon over rye crisps with a mustard-dill sauce and shaved red onion.",
    "swedish-meatballs": "Small tender pork-and-beef meatballs blanketed in a silky cream gravy, served with lingonberry jam and mashed potatoes.",
    "pickled-herring-plate": "Cool, bright pickled herring with red onion and dill, fanned beside boiled potatoes and a slice of dark rye.",
    "danish-pastry-coffee": "A flaky butter-laminated pastry — twisted, sticky, glazed — alongside a hot mug of strong coffee.",
    "moussaka": "Layers of fried eggplant, spiced lamb, and tomato beneath a thick blanket of béchamel, baked until the top is bronzed and bubbling.",
    "spanakopita": "A golden parcel of phyllo wrapped around a savory spinach-and-feta filling — shatteringly crisp on the outside, herby and soft within.",
    "souvlaki-plate": "Charred lemon-oregano pork skewers with warm pita, a scoop of tzatziki, and a tumble of Greek salad.",
    "kung-pao-chicken": "Diced chicken wok-fried with peanuts, dried red chiles, and Sichuan peppercorns in a glossy sweet-tart sauce.",
    "sweet-and-sour-pork": "Crisp battered pork cubes glazed in a glossy red sauce with pineapple, green pepper, and onion.",
    "mapo-tofu": "Soft cubes of tofu in a fierce red-oil sauce of fermented bean paste and Sichuan pepper, threaded with crumbled pork.",
    "dim-sum-platter": "An array of steamer baskets: pleated dumplings, fluffy pork buns, translucent shrimp har gow, and a small lake of soy.",
    "jiaozi-pork-cabbage": "Half-moon pork-and-cabbage dumplings, boiled or pan-fried with a crisp bottom, served with a black vinegar dip.",
    "xiao-long-bao": "Delicate Shanghai soup dumplings pleated at the top — pierce, sip the hot broth, then bite the pork filling.",
    "wonton-soup": "Slippery pork-and-shrimp wontons floating in a clear ginger-scallion broth — clean, light, and warming.",
    "congee-rice": "Long-simmered rice porridge — silky, savory, ladled into bowls with shredded chicken, scallions, and a drizzle of sesame oil.",
    "peking-duck": "Crackling lacquered duck skin, fanned slices of breast, and steamed pancakes for rolling with scallion, cucumber, and hoisin.",
    "lions-head-meatball": "Oversized tender pork meatballs braised slowly in a savory broth with a nest of napa cabbage.",
    "yuxiang-eggplant": "Tender braised eggplant in a fish-fragrant sauce — sweet, sour, garlicky, and threaded with minced pork.",
    "twice-cooked-pork": "Slices of pork belly first simmered, then stir-fried with leeks and chiles in a smoky fermented-bean sauce.",
    "dan-dan-noodles": "Springy noodles in a chili-oil-and-sesame sauce topped with crispy minced pork and pickled mustard greens — toss to combine.",
    "fried-rice-egg": "Day-old rice flashed in a hot wok with scrambled egg, soy, scallion, and a hit of sesame oil — quick, comforting, satisfying.",
    "char-siu-pork-rice": "Glossy lacquered slices of barbecued pork fanned over steamed white rice with bok choy and a drizzle of pan juices.",
    "sichuan-hot-pot": "A bubbling fiery red broth at the center of the table for cooking thin-sliced meat, tofu, mushrooms, and noodles to order.",
    "salt-pepper-shrimp": "Whole shell-on shrimp wok-tossed with chiles, garlic, and a Sichuan-pepper-and-salt mix — fragrant, crackling, eat-the-shells.",
    "sushi-nigiri-platter": "Hand-pressed mounds of seasoned rice topped with glistening slices of tuna, salmon, shrimp, and mackerel, with a dab of wasabi.",
    "ramen-tonkotsu": "A cloudy pork-bone broth simmered for hours, with springy noodles, chashu pork, ajitama egg, scallion, and bamboo shoots.",
    "ramen-shoyu": "A clear soy-tinted broth over wavy noodles, topped with chashu pork, marinated egg, nori, and a sprinkle of scallion.",
    "ramen-miso": "A nutty-rich miso-laced broth over thick chewy noodles, finished with sweet corn, butter, ground pork, and bean sprouts.",
    "donburi-gyudon": "Thin-sliced beef simmered in a sweet-savory soy-mirin sauce with onion, ladled over hot rice with a soft pickled egg.",
    "donburi-oyakodon": "Chicken and softly set egg simmered together in a sweet dashi-soy broth, blanketed over steamed rice — \"parent-and-child\" bowl.",
    "donburi-katsudon": "A breaded pork cutlet, fried crisp then simmered with onion and egg in a sweet-savory broth, served over rice.",
    "tempura-platter": "Shrimp and seasonal vegetables in a lacy, ice-cold batter, flash-fried until weightlessly crisp, served with a tentsuyu dipping sauce.",
    "okonomiyaki": "A savory cabbage pancake stuffed with pork, drizzled with Kewpie mayo and a sweet-sour brown sauce, finished with dancing bonito flakes.",
    "soba-noodles": "Cool buckwheat noodles served on a bamboo mat with a chilled dipping sauce, scallions, and a touch of wasabi.",
    "udon-noodles": "Thick chewy noodles in a clear dashi broth, topped with tempura, scallion, and a swirl of soy.",
    "tonkatsu-plate": "A panko-crusted pork cutlet fried to a crackling gold, sliced and served with shredded cabbage, rice, and a tangy brown sauce.",
    "sukiyaki": "Thin-sliced beef and tofu simmered tableside with vegetables in a sweet soy-mirin broth, dipped into a raw beaten egg.",
    "shabu-shabu": "Paper-thin beef swished through a clear hot broth at the table, dipped into sesame or ponzu sauce with rice on the side.",
    "bibimbap": "A stone bowl of warm rice topped with neat piles of seasoned vegetables, beef, and a runny egg — stirred together with gochujang.",
    "bulgogi-plate": "Marinated thin slices of beef grilled fast and hot, served with rice, lettuce wraps, and an array of small banchan dishes.",
    "kimbap": "Seasoned rice and a colorful line of fillings — egg, spinach, carrot, beef or imitation crab — rolled in nori and sliced into rounds.",
    "kimchi-jjigae": "A bubbling red stew of aged kimchi, pork belly, tofu, and scallion — sour, spicy, and deeply comforting.",
    "sundubu-jjigae": "A volcanic-red bowl of silken tofu, seafood, and chili oil cracked with a raw egg at the table, served with rice.",
    "korean-bbq": "Marinated short ribs, pork belly, and chicken grilled at the table, wrapped in lettuce leaves with rice, ssamjang, and pickles.",
    "japchae": "Glassy sweet potato noodles tossed with sesame oil, soy, beef, and a rainbow of julienned vegetables.",
    "samgyetang": "A whole young chicken stuffed with sweet rice, ginseng, and jujubes, simmered in a milky broth — a restorative Korean classic.",
    "tteokbokki": "Chewy cylindrical rice cakes simmered in a fiery sweet-spicy gochujang sauce with fish cake and scallion.",
    "pad-thai": "Stir-fried rice noodles in a sweet-sour tamarind sauce with shrimp, egg, bean sprouts, lime, and a scatter of crushed peanuts.",
    "tom-yum-goong": "A clear, fragrant, sour-spicy broth of lemongrass, kaffir lime, and chili swimming with plump shrimp and mushrooms.",
    "green-curry-chicken": "Tender chicken simmered in a fragrant green coconut curry of basil, lime leaf, eggplant, and bird's eye chili.",
    "red-curry-chicken": "Chicken in a velvety red coconut curry of bamboo shoot, basil, and lime — sweet, hot, and creamy.",
    "massaman-curry": "Slow-cooked beef and potato in a mellow, peanut-laced southern Thai curry — warming with cardamom and cinnamon.",
    "som-tam": "Shredded green papaya pounded in a mortar with chiles, lime, fish sauce, palm sugar, peanuts, and tomato — crunchy, sour, fiery.",
    "larb": "Minced chicken or pork tossed warm with toasted rice powder, mint, lime, fish sauce, and red chili — eaten in lettuce cups.",
    "khao-soi": "Egg noodles in a coconut-curry broth with braised chicken, topped with crispy fried noodles, pickled mustard greens, and shallot.",
    "pad-see-ew": "Wide rice noodles charred in the wok with Chinese broccoli, egg, and a sweet dark soy — smoky, savory, sturdy.",
    "pho-bo": "Translucent rice noodles in a clear cinnamon-and-star-anise beef broth with rare slices of beef, basil, lime, and bean sprouts on the side.",
    "pho-ga": "A clean chicken broth over rice noodles with poached chicken, scallion, cilantro, and a squeeze of lime — Vietnamese soothing.",
    "banh-mi": "A crisp baguette stuffed with pork, pâté, pickled daikon and carrot, cilantro, jalapeño, and a slick of mayo — crunch, brightness, heat.",
    "bun-bo-hue": "A bold spicy lemongrass beef-and-pork broth over thick round rice noodles, topped with herbs, lime, and chili paste.",
    "summer-rolls": "Translucent rice-paper rolls wrapped around shrimp, vermicelli, lettuce, and mint, served with a peanut-hoisin dipping sauce.",
    "bun-cha": "Charred pork patties and grilled pork belly in a sweet-sour fish sauce broth, served with rice noodles and a basket of herbs.",
    "com-tam": "Broken rice topped with a grilled lemongrass pork chop, a shredded pork-skin mix, a fried egg, and pickled vegetables.",
    "nasi-goreng": "Indonesian fried rice with kecap manis and shrimp paste, topped with a fried egg, fried shallots, and a few prawn crackers.",
    "rendang": "Beef simmered for hours in coconut milk and spice paste until the liquid disappears and the meat is darkly fragrant and tender.",
    "laksa": "A coconut-and-chili-rich noodle soup with shrimp, tofu puffs, bean sprouts, and a swirl of sambal — Southeast Asian comfort.",
    "satay-plate": "Skewers of grilled marinated chicken or beef glistening with peanut sauce, served with cucumber, rice cake, and a lime wedge.",
    "gado-gado": "Steamed and blanched vegetables, tofu, tempeh, and hard-boiled egg dressed with a rich peanut sauce — Indonesia's composed salad.",
    "mee-goreng": "Yellow wheat noodles wok-fried with shrimp, egg, tofu, and chili-tomato seasoning — sweet, spicy, and tangy.",
    "chicken-adobo": "Chicken braised in soy, vinegar, garlic, and bay until the sauce reduces to a glossy savory glaze — the Filipino home classic.",
    "sinigang": "A sour tamarind-laced broth bobbing with pork ribs, water spinach, daikon, and tomato — bracing and deeply comforting.",
    "lumpia": "Slim spring rolls of pork and vegetables fried golden and shattering-crisp, served with a sweet-and-sour dip.",
    "kare-kare": "Oxtail and tripe stewed in a thick peanut-and-annatto sauce with eggplant and bok choy, served with shrimp paste on the side.",
    "pancit": "Stir-fried rice noodles tossed with chicken, shrimp, and vegetables in a savory soy sauce — a Filipino birthday staple.",
    "butter-chicken": "Tender tandoor-cooked chicken simmered in a velvety tomato-cream sauce sweetened with fenugreek and butter, eaten with naan.",
    "chicken-tikka-masala": "Charred yogurt-marinated chicken bobbing in a richly spiced tomato-cream sauce — the Anglo-Indian crowd-pleaser.",
    "vindaloo-pork": "Pork braised in a fiery vinegar-and-chile masala — Goan, hot, tangy, and deep.",
    "chicken-korma": "Chicken simmered gently in a mild, fragrant cream-and-cashew sauce flecked with cardamom and saffron.",
    "rogan-josh": "Slow-cooked lamb in a Kashmiri sauce blushing red with chili and aromatic with fennel and ginger.",
    "chicken-biryani": "Long-grain basmati layered with saffron-marinated chicken and fried onions, steamed until perfumed with cardamom and clove.",
    "paneer-tikka": "Cubes of fresh cheese marinated in spiced yogurt, threaded on skewers with peppers and onion, and charred in a tandoor.",
    "palak-paneer": "Cubes of soft paneer simmered in a vivid spinach purée seasoned with garlic, ginger, and fenugreek — eaten with warm roti.",
    "dal-makhani": "Black lentils and kidney beans slow-cooked with cream and butter until impossibly silky, finished with a smoky tempering.",
    "dal-tadka": "Yellow split lentils simmered until soft, finished with a sizzling tadka of ghee, cumin, mustard seed, and dried chili.",
    "masala-dosa": "A paper-thin, lacy fermented-rice crêpe wrapped around a spiced potato filling, served with coconut chutney and sambar.",
    "idli-sambar": "Pillowy steamed rice-and-lentil cakes served with a fragrant lentil-vegetable stew and coconut chutney for dipping.",
    "vegetarian-thali": "A round metal platter holding small bowls of curries, dal, rice, raita, and pickles — a tour of flavors at one meal.",
    "samosa-chaat": "Crispy samosas crumbled into a bowl, drowned in chickpea curry, tangy tamarind, mint chutney, yogurt, and crunchy sev.",
    "chana-masala": "Chickpeas simmered in a robust tomato-onion-spice gravy brightened by amchur and ginger — eaten with bhatura or rice.",
    "aloo-gobi": "Potato and cauliflower tossed dry-style with turmeric, cumin, and ginger until tender and just crisp at the edges.",
    "tandoori-chicken": "Yogurt-and-spice marinated chicken charred in a tandoor until smoky and stained red, served with onion rings and lemon.",
    "rajma": "Red kidney beans simmered slowly in a tomato-onion masala — Punjabi home comfort, ladled over plain rice.",
    "nihari": "A slow-cooked beef shank stew finished with ginger, lemon, and fried shallots — eaten at dawn with naan.",
    "haleem": "A long-cooked porridge of wheat, lentils, and shredded meat seasoned with garam masala — thick, savory, and rib-sticking.",
    "pakistani-biryani-mutton": "Layered mutton biryani heavy with garam masala, fried onions, and saffron — fragrant, fiery, and meant for sharing.",
    "fish-curry-bengali": "Fish steaks simmered in a mustard-oil-and-poppy-seed gravy bright with green chili and turmeric — eaten with steamed rice.",
    "chapli-kebab": "Flat spiced minced-beef patties studded with pomegranate seeds and green chili, shallow-fried until edges crisp.",
    "rice-and-curry-sri-lankan": "A mound of rice surrounded by small servings of fiery, fragrant curries — fish, dal, coconut sambol, and more.",
    "hoppers": "Bowl-shaped fermented rice-and-coconut pancakes with crisp edges and a soft center, often with an egg cracked into the middle.",
    "kottu-roti": "Shredded roti stir-fried on a hot griddle with vegetables, egg, and curry — chopped with a rhythmic clang, served piping hot.",
    "mezze-plate": "A spread of small dishes — hummus, baba ganoush, tabbouleh, olives, pickles, and warm pita — meant for grazing.",
    "baba-ganoush": "Smoky roasted eggplant whipped with tahini, lemon, and garlic — silky, char-tinged, scooped with warm pita.",
    "tabbouleh": "A bright bulgur salad heavy with chopped parsley and mint, tossed with tomato, lemon, and olive oil.",
    "fattoush": "A crunchy salad of cucumber, tomato, radish, and herbs tossed with toasted pita shards and a sumac-tart dressing.",
    "kibbeh": "Footballs of bulgur shell stuffed with spiced minced lamb and pine nuts, fried to a deep mahogany.",
    "shawarma-chicken": "Spit-roasted spiced chicken, shaved off the column into a warm wrap with garlic sauce, pickles, and tomato.",
    "shawarma-beef": "Layered, spiced beef shaved from the rotating spit and tucked into pita with tahini, pickles, and onion.",
    "manakish-zaatar": "A flatbread brushed with olive oil and za'atar, baked until the herbs are fragrant and the edges blistered.",
    "kafta-kebab": "Skewers of seasoned minced lamb with parsley and onion, charred over coals and served with tahini and pita.",
    "fatteh": "Toasted pita layered with chickpeas, garlicky yogurt, and a glug of warm browned butter — comfort with crunch underneath.",
    "falafel-plate": "Crisp-shelled herbed chickpea fritters scattered over salad with tahini, hummus, pickles, and warm pita.",
    "kabab-koobideh": "Skewers of seasoned minced lamb pressed long and thin, char-grilled and served over saffron rice with grilled tomato.",
    "ghormeh-sabzi": "A deeply green Persian herb stew with lamb, dried lime, and red kidney beans — sour, savory, slow-cooked.",
    "fesenjan": "A Persian stew of chicken or duck in a glossy walnut-and-pomegranate sauce — sweet-tart, dark, and silky.",
    "tahdig-saffron": "The prized crisp golden crust at the bottom of a pot of saffron rice — buttery, crackling, fought over.",
    "ash-reshteh": "A thick Persian noodle soup with herbs, beans, and lentils, finished with kashk, fried mint, and crispy onion.",
    "adana-kebab": "Minced lamb seasoned with red pepper, pressed onto wide skewers and grilled over charcoal — smoky and bold.",
    "doner-kebab": "Layered seasoned meat roasted on a vertical spit, shaved into pita or a wrap with salad, pickles, and garlic sauce.",
    "iskender-kebab": "Sliced döner meat fanned over torn pide bread, blanketed in tomato sauce and a final pour of foaming butter and yogurt.",
    "dolma-stuffed-grape-leaves": "Tender grape leaves rolled tight around a lemony rice-and-herb filling, served chilled with a wedge of lemon.",
    "borek-cheese": "Coils of buttery, paper-thin phyllo wrapped around a salty cheese filling, baked until the crust crackles.",
    "lahmacun": "A crisp, thin Turkish flatbread spread with minced lamb, onion, and pepper, rolled with parsley and a squeeze of lemon.",
    "kunefe": "Shredded phyllo layered over melting cheese, baked golden, soaked in rose-scented syrup, and topped with crushed pistachio.",
    "chicken-tagine": "Chicken slow-braised in a clay pot with olives, preserved lemon, and saffron — bright, briny, and tender.",
    "lamb-tagine": "Lamb stewed slowly with prunes, almonds, cinnamon, and honey until the meat falls apart and the sauce turns deeply sweet.",
    "moroccan-couscous": "Steamed semolina mounded high under a stew of slow-cooked lamb and seven vegetables in a fragrant broth.",
    "harira": "A tomato-based Moroccan soup thick with lentils, chickpeas, lamb, and herbs — traditionally eaten to break a fast.",
    "ful-medames": "Slow-stewed fava beans mashed with olive oil, lemon, cumin, and garlic, scooped with warm flatbread.",
    "koshari": "An Egyptian street pile of rice, lentils, macaroni, and chickpeas crowned with crispy onions and a tangy tomato sauce.",
    "brik": "A paper-thin Tunisian phyllo turnover folded over tuna, parsley, and a runny egg, fried until shatter-crisp.",
    "shakshuka": "Eggs poached in a spiced tomato-and-pepper sauce in a sizzling skillet, scooped with bread and finished with crumbled feta.",
    "bstilla": "A Moroccan layered phyllo pie of shredded chicken or pigeon, almonds, and cinnamon, dusted with powdered sugar — sweet meets savory.",
    "mloukhia": "A glossy, almost-thick green stew of finely chopped jute leaves with meat or chicken, ladled over rice or eaten with bread.",
    "meze-turkish": "A spread of small Turkish plates: yogurt-cucumber cacık, smoky eggplant, stuffed peppers, white cheese, and warm pide.",
    "jollof-rice": "Long-grain rice cooked deep red in a tomato-pepper-onion sauce, smoky from the bottom of the pot — West Africa's most-debated dish.",
    "egusi-soup": "A thick Nigerian stew of ground melon seed, palm oil, leafy greens, and meat — eaten with a ball of fufu or pounded yam.",
    "suya-skewers": "Thin-sliced beef rubbed with a peanut-and-chili spice blend and grilled over charcoal, served with raw onion and tomato.",
    "fufu-and-stew": "A smooth, stretchy starch ball torn by hand and dipped into a rich palm-nut or groundnut stew with goat or fish.",
    "peanut-stew": "A West African stew of chicken or beef simmered in a thick peanut-tomato sauce, served over rice with greens.",
    "waakye": "Ghanaian rice and beans cooked with sorghum leaves into a russet base, served with stew, fried plantain, gari, and shito.",
    "thieboudienne": "Senegal's national plate: spiced fish over jollof-style red rice with cabbage, eggplant, cassava, and a slick of lime.",
    "injera-doro-wat": "Tangy spongy injera torn and dipped into doro wat — chicken and hard-boiled egg in a deep berbere stew.",
    "injera-misir-wat": "Red split lentils simmered with berbere into a glossy stew, scooped with torn rounds of sour injera.",
    "injera-alicha": "A mild yellow Ethiopian stew of vegetables or chicken seasoned with turmeric and ginger, eaten with injera.",
    "ugali-sukuma-wiki": "A firm cornmeal porridge pinched into bites and dipped into sukuma wiki — sautéed greens with onion and tomato.",
    "pilau-east-african": "Long-grain rice cooked in a spiced broth with cardamom, clove, and cinnamon, threaded with tender beef and onion.",
    "bobotie": "A South African baked dish of curried minced beef sweetened with raisin, topped with an egg-milk custard.",
    "bunny-chow": "A hollowed half-loaf of bread filled with a fragrant Durban-style curry — eat from the inside out with your hands.",
    "pap-chakalaka": "A firm white maize porridge served with chakalaka — a spicy relish of beans, carrot, pepper, and tomato.",
    "biltong-plate": "Strips of dried, spiced South African beef sliced thin and served with cubes of cheese and crisp crackers.",
    "tacos-al-pastor": "Marinated pork shaved from a vertical spit onto small charred corn tortillas, finished with pineapple, onion, and cilantro.",
    "tacos-carnitas": "Slow-braised, crisped-edge pork piled into warm corn tortillas with diced onion, cilantro, and a squeeze of lime.",
    "tacos-fish": "Beer-battered or grilled white fish in a soft corn tortilla with shredded cabbage, lime crema, and a hit of hot sauce.",
    "tacos-lengua": "Slow-braised, tender beef tongue, diced fine, served on small corn tortillas with onion, cilantro, and salsa verde.",
    "tacos-barbacoa": "Slow-steamed beef or lamb pulled into juicy strands, tucked into warm corn tortillas with chopped onion and cilantro.",
    "enchiladas-rojas": "Corn tortillas rolled around shredded chicken, smothered in a dark red chile sauce, melted cheese, and crema.",
    "mole-poblano-chicken": "Chicken bathed in mole poblano — a deep, glossy sauce of dried chiles, nuts, seeds, spices, and a hint of chocolate.",
    "tamales": "Steamed corn-husk packets of soft masa hiding a savory pork, chicken, or rajas filling — unwrap and eat warm.",
    "chilaquiles": "Crispy tortilla wedges simmered in a red or green salsa until just softened, topped with eggs, crema, queso fresco, and onion.",
    "pozole-rojo": "A red-chile hominy stew with tender pork, garnished tableside with shredded cabbage, radish, lime, and oregano.",
    "sopes": "Thick masa rounds with pinched edges holding refried beans, shredded chicken, lettuce, crema, and crumbled cheese.",
    "huevos-rancheros": "Sunny-side eggs on a lightly fried tortilla, blanketed in warm ranchero salsa, with beans and avocado on the side.",
    "feijoada": "A deep, slow-cooked Brazilian stew of black beans with smoked meats, served with rice, collards, and orange slices.",
    "moqueca": "A coconut-milk Brazilian fish stew in a clay pot, glossy with palm oil and bright with cilantro, tomato, and pepper.",
    "churrasco-plate": "An assortment of fire-roasted meats sliced tableside — picanha, sausage, chicken hearts — served with rice, beans, and farofa.",
    "pao-de-queijo": "Chewy, cloud-light Brazilian cheese rolls, crisp outside and stretchy within — eaten warm by the handful.",
    "acaraje": "Black-eyed-pea fritters fried in palm oil, split open and stuffed with shrimp and a fiery vatapa paste — a Bahian street snack.",
    "vatapa": "A creamy Bahian stew of bread, ground peanuts, coconut milk, and shrimp, thickened until spoon-coats and tinted orange by palm oil.",
    "ceviche-peruvian": "Diced raw fish cured briefly in lime juice with chile and red onion, served with sweet potato and toasted corn.",
    "lomo-saltado": "Strips of beef wok-fired with onion, tomato, and aji amarillo, tossed with French fries and served over rice — Peru meets China.",
    "aji-de-gallina": "Shredded chicken in a creamy aji-amarillo-and-walnut sauce, served over potato slices with olives and a hard-boiled egg.",
    "anticuchos": "Skewers of marinated grilled beef heart, charred over coals and served with potato and a green aji sauce.",
    "papa-huancaina": "Cool boiled potato slices blanketed in a creamy aji-amarillo-and-fresh-cheese sauce, plated with olives and egg.",
    "asado-plate": "An Argentine fire-grilled mixed plate of beef short rib, sausage, sweetbreads, and morcilla, served with chimichurri.",
    "milanesa": "A breaded, hammered-thin beef cutlet fried golden and topped with lemon — sturdy, family-style Argentine comfort.",
    "empanadas-argentine": "Half-moon pastries pinched along the edge, baked or fried, holding spiced beef, olives, and egg.",
    "chimichurri-steak": "A thick grilled steak rested and sliced, drowned in a sharp parsley-garlic-oregano-vinegar chimichurri.",
    "jerk-chicken": "Chicken marinated in scotch bonnet, allspice, and thyme, then slow-grilled until the skin is lacquered and smoky.",
    "ackee-saltfish": "Salt cod sautéed with onion, pepper, and tomato, folded gently with buttery ackee — Jamaica's national breakfast.",
    "ropa-vieja": "Tender shredded beef slow-cooked in tomato, pepper, onion, and olives — \"old clothes,\" served with rice and plantains.",
    "jamaican-oxtail": "Oxtail braised long with butter beans in a deep, sticky gravy seasoned with allspice and thyme.",
    "callaloo": "Stewed leafy callaloo (or amaranth) cooked with onion, garlic, tomato, and a touch of pepper — eaten as a side or with bread.",
    "caribbean-roti": "A soft flaky flatbread folded around a curry of goat, chicken, or vegetable with potato and chickpea.",
    "cuban-sandwich": "Roast pork, ham, Swiss, mustard, and pickles pressed in Cuban bread until the cheese melts and the crust crackles.",
    "mofongo": "Mashed green plantain pounded with garlic and pork crackling, formed into a dome, often filled with shrimp or stew.",
    "arepas": "Crisp-shelled corn cakes split open and stuffed with cheese, shredded beef, or black beans — a Venezuelan-Colombian staple.",
    "pupusas": "Thick handmade cornmeal cakes stuffed with cheese, beans, or pork, griddled and served with curtido and salsa roja.",
    "gallo-pinto": "Costa Rican rice and black beans cooked together with onion, pepper, and Lizano sauce, served at breakfast with eggs.",
    "baleadas": "A soft flour tortilla folded around refried beans, crumbled cheese, and crema — a portable Honduran lunch.",
    "haitian-griot": "Citrus-marinated pork shoulder braised then fried until crackling on the outside and juicy within, served with pikliz.",
    "tostones": "Twice-fried green plantain rounds, smashed flat and salted — crackling outside, soft inside, eaten with garlic dipping sauce.",
    "arroz-con-pollo": "One-pot saffron-yellow rice studded with chicken, peas, peppers, and olives — a Sunday meal across Latin America.",
    "charcuterie-board": "A board of cured meats, hard and soft cheeses, mustards, pickles, dried fruit, nuts, and crackers — built for grazing.",
    "antipasto-platter": "An Italian spread of cured meats, marinated vegetables, olives, cheeses, and bread — served before a meal or as one.",
    "popcorn-buttered": "Hot-air-popped kernels tossed with melted butter and salt — light, crunchy, addictive.",
    "popcorn-caramel": "Popped kernels coated in a glossy caramel and baked until brittle, then broken into sticky-crisp clusters.",
    "chips-and-salsa": "Crisp salted tortilla chips beside a bowl of chunky, lime-bright tomato salsa.",
    "chips-and-guacamole": "Tortilla chips for scooping a green, lime-tart, chunky mash of avocado with onion, cilantro, and chile.",
    "chips-and-queso": "Tortilla chips dunked into a warm pool of melted cheese, fired up with green chile.",
    "nut-mix-roasted": "A warm mix of roasted, salted nuts — almonds, cashews, pecans — with a glossy oil sheen.",
    "trail-mix": "A handful of nuts, dried fruit, and chocolate pieces — sweet, salty, energizing.",
    "crudite-platter": "Cool, raw vegetables — carrot, cucumber, celery, radish — arrayed around a bowl of creamy dip.",
    "fruit-platter": "Wedges of melon, pineapple, strawberries, and grapes, fanned in colorful arcs on a wide platter.",
    "snack-board-mediterranean": "A grazing board of hummus, olives, marinated feta, cucumber, pita, and roasted red peppers.",
    "pretzels-mustard": "Crunchy salted pretzels alongside a small bowl of sharp, grainy mustard for dipping.",
    "chocolate-cake-slice": "A wedge of moist chocolate cake layered with fudgy ganache and topped with curls of bittersweet chocolate.",
    "carrot-cake-slice": "Moist spiced carrot cake studded with walnut and raisin, capped with a thick cream-cheese frosting.",
    "cheesecake-plain": "A tall slice of dense, tangy New York cheesecake on a buttery graham crust, with a faint vanilla aroma.",
    "cheesecake-strawberry": "A cool slab of cheesecake topped with halved strawberries glistening in a glossy red glaze.",
    "tres-leches-cake": "A sponge soaked through with three milks, pillowy and dripping-sweet, finished with whipped cream and cinnamon.",
    "red-velvet-cake": "Crimson cocoa cake layered with tangy cream-cheese frosting — dramatic on the cut, soft in the bite.",
    "apple-pie": "A double-crust pie of cinnamon-spiced apples beneath a flaky lattice, the filling syrupy and the crust bronzed.",
    "pumpkin-pie": "A spiced pumpkin custard set in a flaky pie shell, topped with a soft cloud of whipped cream.",
    "pecan-pie": "A buttery shell holding a glossy brown-sugar filling crammed with toasted pecan halves — sticky-sweet at the heart.",
    "key-lime-pie": "A tart, pale-yellow lime custard set into a buttery graham crust, topped with whipped cream and zest.",
    "ice-cream-sundae": "Scoops of vanilla ice cream drowned in hot fudge, crowned with whipped cream, peanuts, and a cherry on top.",
    "tiramisu": "Espresso-soaked ladyfingers layered with sweet mascarpone cream and dusted with cocoa — light, boozy, and silken.",
    "halwa-semolina": "Toasted semolina cooked in ghee with sugar, cardamom, and milk, studded with raisin and slivered almond.",
    "mochi-ice-cream": "Cold ice cream wrapped in a chewy, cool sleeve of mochi rice dough — one-bite contrast of soft and creamy.",
    "churros-chocolate": "Hot ridged dough fried golden, dusted in cinnamon sugar, served with a thick mug of melted dark chocolate for dipping.",
    "creme-brulee": "A vanilla custard set firm beneath a shattering layer of caramelized sugar — crack the top with a spoon.",
    "panna-cotta": "A trembling chilled cream pudding unmolded onto a plate, served with a slick of berry sauce.",
    "crepe-suzette": "Lacy crepes folded into a butter-orange-Grand-Marnier sauce, flamed at the table to a glaze.",
    "bread-pudding": "Cubed stale bread soaked in a vanilla-egg custard with raisin, baked until the top is crisp and the inside spoon-soft.",
    "chocolate-fondue": "A warm pot of melted chocolate kept gently bubbling, with fruit, marshmallow, and cake for dipping.",
    "affogato": "A scoop of cold vanilla gelato \"drowned\" by a fresh hot espresso poured over the top — Italy's two-ingredient finale.",
    "green-smoothie": "Blended spinach or kale with banana, apple, and ice — bright green, vegetal, just-sweet, and cold.",
    "protein-smoothie": "Banana, whey or plant protein, milk, and peanut butter blended thick and frothy — post-workout fuel.",
    "vanilla-latte": "A double shot of espresso pulled into steamed milk with a hint of vanilla syrup, finished with a thin layer of foam.",
    "masala-chai-latte": "Black tea simmered with milk, cardamom, ginger, clove, and pepper — fragrant, sweet, and warming.",
    "matcha-latte": "Stone-ground green tea whisked into steamed milk to a vivid jade green, lightly sweetened.",
    "boba-milk-tea": "Sweet milk tea over chewy, dark tapioca pearls — sipped with a wide straw over ice.",
    "sweet-lassi": "Whipped yogurt thinned with milk and sweetened with sugar, served cold — Punjabi summer refreshment.",
    "mango-lassi": "Yogurt blended with sweet mango pulp and a pinch of cardamom — thick, golden, and cooling.",
    "horchata-mexican": "A chilled rice-and-cinnamon drink sweetened with sugar — milky, fragrant, served over ice.",
    "agua-fresca-watermelon": "Watermelon blended with water, lime, and a touch of sugar — strained, chilled, and impossibly refreshing.",
    "hot-chocolate": "Steamed milk whisked with dark chocolate, topped with whipped cream or marshmallows — winter in a mug.",
    "turkish-coffee": "Unfiltered finely-ground coffee simmered with sugar in a small copper pot, served in a tiny cup with the grounds settling.",
    "continental-breakfast": "A simple morning spread: croissants, butter, jam, fruit, yogurt, and coffee — light and fast.",
    "afternoon-tea-spread": "A tiered stand of finger sandwiches, scones with clotted cream and jam, and small cakes, beside a pot of strong black tea.",
    "brunch-platter": "A late-morning combo plate: eggs, bacon, toast, hash browns, fresh fruit, and a glass of orange juice.",
    "kids-lunchbox": "A lunchbox of small pieces — a sandwich, cheese cubes, fruit slices, a few crackers, and a cookie.",
    "bistro-plate": "A simple French bistro plate: roast chicken, salad with vinaigrette, crusty bread, and a glass of red.",
    "japanese-breakfast": "A traditional set: grilled fish, miso soup, steamed rice, pickles, and a small bowl of natto or rolled egg.",
    "dim-sum-brunch": "A weekend table of steamer baskets — dumplings, buns, rice rolls, egg tarts — chased with hot tea.",
    "indian-breakfast": "Soft idli or crisp dosa with sambar and coconut chutney, alongside hot filter coffee.",
}


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.dirname(here)
    path = os.path.join(repo, 'src', 'data', 'meals.json')

    with open(path, 'r', encoding='utf-8') as fh:
        meals = json.load(fh)

    updated = 0
    missing = []
    for meal in meals:
        new = NOTES.get(meal['id'])
        if new:
            meal['notes'] = new
            updated += 1
        else:
            missing.append(meal['id'])

    with open(path, 'w', encoding='utf-8') as fh:
        json.dump(meals, fh, ensure_ascii=False, indent=2)
        fh.write('\n')

    print(f'Updated {updated}/{len(meals)} meal notes.')
    if missing:
        print(f'Missing {len(missing)} ids — first few: {missing[:5]}')


if __name__ == '__main__':
    main()
